frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.vue, frontend/src/components/header/HeaderComponent.vue, frontend/src/store/useUserStore.js
- scss npm install로 추가
- 헤더에 사용한 font-awesome을 index.html에 추가
- 아직 axios 사용 안 해서 useUserStore에 주석
- 헤더 컴포넌트 추가
=> [Feat] 헤더 추가

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/components/wiki/WikiRegisterComponent.vue, frontend/src/main.js, frontend/src/pages/wiki/WikiRegisterPage.vue, frontend/src/router/index.js
- 위키 등록 컴포넌트
- 위키 등록 페이지
- v-md-editor 설치
- tailwindcss -> public-index.html에 추가
=> [Feat] 위키 등록 컴포넌트, 페이지 개발 (#78)

backend/src/main/java/org/example/backend/Chat/Model/Entity/Chat.java, backend/src/main/java/org/example/backend/Chat/Model/Entity/ChatRoom.java, backend/src/main/java/org/example/backend/EmailVerify/Model/Entity/EmailVerify.java, backend/src/main/java/org/example/backend/Point/Model/Entity/PointDetail.java, backend/src/main/java/org/example/backend/User/Model/Entity/User.java
=> [Feat] User, Chat, ChatRoom, EmailVerify, PointDetail 엔티티 생성

backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorArchive.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorLike.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorScrap.java
=> [Feat] 에러 아카이브 엔티티 생성

backend/src/main/java/org/example/backend/Common/BaseException.java, backend/src/main/java/org/example/backend/Common/BaseResponse.java, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
close #121 
##
```
{
"code": 1000,
"message": "요청이 성공하였습니다."
}
{
"code": 1000,
"message": "요청이 성공하였습니다."
"result": "결과값"
}
{
"code": 40000,
"message": "요청이 실패하였습니다."
}
```
=> [Feat] BaseResponse 생성 (#121)

backend/src/main/java/org/example/backend/Category/Controller/CategoryController.java, backend/src/main/java/org/example/backend/Category/Model/Entity/Category.java, backend/src/main/java/org/example/backend/Category/Model/Res/SuperCategoryRes.java, backend/src/main/java/org/example/backend/Category/Repository/CategoryRepository.java, backend/src/main/java/org/example/backend/Category/Service/CategoryService.java
- /category/super 로 상위 카테고리(id, categoryName) 목록 조회 가능
=> [Feat] 상위 카테고리 목록 조회 (#50)

backend/src/main/java/org/example/backend/Category/Controller/CategoryController.java, backend/src/main/java/org/example/backend/Category/Model/Res/SubCategoryRes.java, backend/src/main/java/org/example/backend/Category/Repository/CategoryRepository.java, backend/src/main/java/org/example/backend/Category/Service/CategoryService.java
- /category/sub 로 superCategoryId와 같이 요청 보냈을 때 하위 카테고리 목록 반환 추가
=> [Feat] 하위 카테고리 목록 조회 추가 (#51)

frontend/src/components/Chat/ChatRoomComponent.vue, frontend/src/store/useChatStore.js, frontend/vue.config.js
close #85 
- 백엔드 채팅방 조회 API를 호출하여 실제 DB에 저장된 값 불러오도록 수정
- 마지막 채팅 날짜가 오늘이면 시간을 표시, 오늘이 아니면 날짜가 표시되도록 수정
- proxy 설정
- CORS 해결
=> [Feat] 채팅방 조회 api 연결 (#85)

backend/.gitignore, backend/docker-compose.yml
```
services:
mariadb:
image: mariadb:latest
environment:
MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
MARIADB_DATABASE: ${DB_DATABASE}
ports:
- "3306:3306"
volumes:
- ./db/:/var/lib/mysql
```
- .gitignore에 db 폴더 추가
=> [Feat] docker-compose.yml 생성

backend/build.gradle, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/Config/Filter/JwtFilter.java, backend/src/main/java/org/example/backend/Config/Filter/LoginFilter.java, backend/src/main/java/org/example/backend/Config/SecurityConfig.java, backend/src/main/java/org/example/backend/Exception/custom/InvalidUserException.java, backend/src/main/java/org/example/backend/Security/CustomUserDetailService.java, backend/src/main/java/org/example/backend/Security/CustomUserDetails.java, backend/src/main/java/org/example/backend/User/Repository/UserRepository.java, backend/src/main/java/org/example/backend/Util/JwtUtil.java, backend/src/main/resources/application.yml
close #4 
- spring-security 적용
- loginFilter에 로그인에 성공했을 때 쿠키에 JWT 토큰 추가 및 유저 ID 반환하게 함
- 추후에 관리자 생기면 role 관련 주석 되어있는 부분 살려서 구현
프론트쪽에 접속해 로그인 로직이 정상적으로 굴러가는지 확인해주세용
=> [Feat] 일반 로그인 기능 추가 (#4)

frontend/src/App.vue, frontend/src/components/header/HeaderComponent.vue, frontend/src/components/user/OverlayComponent.vue, frontend/src/components/user/SignInComponent.vue, frontend/src/components/user/SignUpComponent.vue, frontend/src/pages/LoginPage.vue, frontend/src/router/index.js, frontend/src/store/useUserStore.js
회원가입 : #58
close #63 
- 로그인, 회원가입 페이지 ui 구현
- 로그인 api 연결 및 쿠키 설정 추가
/login?mode=login으로 접속해서 테스트 계정 로그인 잘 되고 쿠키도 생기는지 확인해주세용
=> [Feat] 로그인 페이지 추가 (#63)

frontend/src/components/qna/QnaRegisterComponent.vue, frontend/src/router/index.js, frontend/src/store/useQnaStore.js
close #34 
- 질문 등록 페이지 구현
- 각 input 태그에 v-model 연결
- v-model 데이터를 활용한, 취소 및 disable 함수 개발 
- axios 활용 백엔드 /qna 등록 api 연결
=> [Feat] 질문 등록 페이지 구현 및 백엔드 api 연결

frontend/src/components/wiki/WikiRegisterComponent.vue, frontend/src/store/useWikiStore.js
close #78
- axios 연결 중
- 카테고리 연결 미적용
=> [Feat] 위키 등록 axios 연결 기능 (#78)

frontend/src/components/Category/SubCategoryModal.vue, frontend/src/store/useCategoryStore.js
close #65
- 하위 카테고리 등록 버튼을 누르면 alert로 새로 등록할 수 있게 추가
똑같이 props 받았다고 치고 테스트해서 연결해서 테스트 필요
=> [Feat] 하위 카테고리 등록 추가 (#65)

backend/src/main/java/org/example/backend/Chat/Controller/ChatController.java, backend/src/main/java/org/example/backend/Chat/Model/Res/ChatMessageListRes.java, backend/src/main/java/org/example/backend/Chat/Model/Res/ChatMessageRes.java, backend/src/main/java/org/example/backend/Chat/Model/Res/ChatRoomRes.java, backend/src/main/java/org/example/backend/Chat/Repository/ChatRepository.java, backend/src/main/java/org/example/backend/Chat/Service/ChatService.java, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/Exception/custom/InvalidChatException.java
close #54  
채팅방의 채팅 내역을 시간순으로 내림차순 정렬하여 보낸다.
- 채팅방 Id를 요청으로부터 받아 Repository에서 조회한다.
- 채팅방 엔티티의 user_Id와 로그인한 사용자의 Id와 비교하여 같지 않은 user_id의 user를 상대방 user로 판단한다.
- 채팅방 id로 채팅엔티티를 조회한다. 이때 size 20으로 slicing 처리하여 조회
- 채팅엔티티에서 메세지, userId, 보낸 시간을 얻는다.
- 위에서 얻은 데이터들을 종합하여 응답을 보낸다.
```
{
"code": 1000,
"result": {
"recipientNickname": "길동홍",
"recipientId": 2,
"messageList": [
{
"nickname": "홍길동",
"userId": 1,
"message": "채팅 내용5",
"sendTime": "2024-09-09T22:36:48",
"profileImg": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/09/422ab83b-5d82-4e7a-9747-a26107603f6e"
},
{
"nickname": "홍길동",
"userId": 1,
"message": "채팅 내용4",
"sendTime": "2024-09-09T22:34:48",
"profileImg": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/09/422ab8 …
```
=> [Feat] 채팅 내역 조회 API 구현 (#54)

frontend/src/components/wiki/WikiRegisterComponent.vue
close #148 
위키 등록시 에러 부분 삭제했습니다.
=> [Fix] 위키 등록 에러 수정

backend/build.gradle, backend/src/main/java/org/example/backend/Qna/model/Entity/req/CreateQuestionReq.java
=> [Fix] 목록 조회 request에 validation, @NotEmpty 추가

frontend/src/router/index.js
router/index.js에 import가 중복으로 되어있어서 오류 났던거 해결
=> [Fix] router/index.js에 중복 import 제거

frontend/src/store/useUserStore.js
=> [Fix] 로그인 URL 프록시 설정

backend/src/main/java/org/example/backend/Config/SecurityConfig.java
=> [Fix] CORS 설정 해제

backend/src/main/java/org/example/backend/Category/Controller/CategoryController.java, backend/src/main/java/org/example/backend/Category/Model/Req/AddSubCategoryReq.java, backend/src/main/java/org/example/backend/Category/Repository/CategoryRepository.java, backend/src/main/java/org/example/backend/Category/Service/CategoryService.java, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
close #47
- 상위카테고리 id랑 카테고리 이름 오면 저장
없습니당
=> [Feat] 하위 카테고리 등록 추가 (#47)

frontend/src/components/Common/SortTypeComponent.vue, frontend/src/pages/QnaListPage.vue
=> [Feat] 정렬 유형 선택 컴포넌트 추가

backend/src/main/java/org/example/backend/Config/SecurityConfig.java
withCredential을 쓸 경우 프록시 설정을 하더라도 무조건 CORS 설정을 해줘야 한다.
=> [Feat] CORS Origin 설정

.github/CODEOWNERS
자동으로 Reviewers를 달아주기 위해 CODEOWNERS 추가
=> [Docs] CODEOWNERS 추가

backend/src/main/java/org/example/backend/Config/SecurityConfig.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java
close #160
- 로그아웃 요청을 받으면 ATOKEN 쿠키 지울 수 있는 응답 반환 추가
=> [Feat] 로그아웃 추가 (#160)

frontend/src/components/wiki/WikiRegisterComponent.vue, frontend/src/pages/wiki/WikiRegisterPage.vue, frontend/src/store/useWikiStore.js
close #78 
- 위키 등록 시 db의 상위 카테고리 불러오기 연결
- 폼데이터 타입으로 Req, 썸네일 백엔드로 연결
- 등록 시 db에 전부 정상 저장되는지 확인 완료
=> [Fix] 위키등록 axios 수정 완료 (#78)

backend/src/main/java/org/example/backend/User/Controller/UserController.java, backend/src/main/java/org/example/backend/User/Service/UserService.java
close #14, #15
- 이메일, 닉네임 중복 확인 (true, false 반환)
=> [Feat] 이메일, 닉네임 중복 확인 (#14,#15)

backend/src/main/java/org/example/backend/BackendApplication.java, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorArchive.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java, backend/src/main/java/org/example/backend/User/Model/Req/SingupReq.java, backend/src/main/java/org/example/backend/User/Model/Req/UserSignupReq.java, backend/src/main/java/org/example/backend/User/Model/Res/SignupRes.java, backend/src/main/java/org/example/backend/User/Service/UserService.java
close #1 
Content-Type이 application/json 형식인 userSignupReq, Content-Type이 image/jpeg형식인 profileImg를 받아서 회원가입을 함
프로필 이미지가 null이거나 비어있으면 프로필 이미지를 기본값으로  지정해주고, 그렇지 않으면 프로필 이미지 경로를 cloudFileUploadService에 프로필 이미지를 받아서 업로드 함
빈 응답을 반환할때 위 코드와 같이 <String> 추가
=> [Feat] 회원가입 추가(#1)

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/File/Controller/FileUploadController.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java, backend/src/main/java/org/example/backend/User/Model/Entity/User.java, backend/src/main/java/org/example/backend/User/Service/UserService.java
close #이슈번호
- 이미지 업로드 컨트롤러 RequestParam 제거
- 닉네임 수정 추가
- 프로필 이미지 수정 추가
- User 엔티티에 CreatedDate, LastModifiedDate 어노테이션 추가
=> [Feat] 회원 정보(닉네임, 이미지) 수정 추가(#6, #7)

frontend/src/components/qna/QnaListCardComponent.vue, frontend/src/pages/QnaListPage.vue, frontend/src/router/index.js, frontend/src/store/useQnaStore.js, frontend/src/utils/FormatDate.js
close #101 
qna 목록 조회 axios 수정
=> [Fix] 목록 조회 axios 호출 형태 및 date 타입 출력 형태 변경

frontend/public/index.html, frontend/src/components/Common/PaginationComponent.vue, frontend/src/components/Common/SortTypeComponent.vue, frontend/src/components/qna/QnaListCardComponent.vue, frontend/src/pages/QnaListPage.vue, frontend/src/router/index.js, frontend/src/store/useQnaStore.js, frontend/src/utils/FormatDate.js
close #101 
- 정렬 조건 및 페이지네이션 컴포넌트 개발
- qna 목록 조회에 컴포넌트 연결 및 목록 조회 페이지 flex 구조화
=> [Feat] 정렬 조건 및 페이지네이션 컴포넌트 구현 및 qna 목록 조회 연결

frontend/src/router/index.js
router index.js 의 ChatPage import 수정
=> [Fix] router index.js의 ChatPage import 오타 수정

backend/src/main/java/org/example/backend/Point/Controller/PointController.java, backend/src/main/java/org/example/backend/Point/Model/Res/GetMyRankRes.java, backend/src/main/java/org/example/backend/Point/Model/Res/GetPointHistoryRes.java, backend/src/main/java/org/example/backend/Point/Service/PointService.java, backend/src/main/java/org/example/backend/User/Repository/UserRepository.java
✅ 포인트 내역 조회 시 총 페이지 수도 같이 반환 하도록 수정
✅ 나의 포인트 및 랭킹 조회 API 구현
``` json
{
"point": 2000,
"rank": 3
}
```
=> [Feat] 내 포인트 및 랭킹 조회 API 구현

frontend/src/components/wiki/WikiDetailComponent.vue, frontend/src/main.js, frontend/src/pages/WikiDetailPage.vue, frontend/src/router/index.js, frontend/src/store/useWikiStore.js
close #86 
📌 위키 상세조회 기능 axios 적용 및 viewer 처리
- 위키 선택시, 해당 위키의 최신버전 상세조회
- 제목, 내용, 카테고리, 스크랩여부, 버전 반환
- v-md-edtior 프리뷰 모드 적용
목차 생성, 스크랩 여부에 따른 버튼 색 변경 처리, 스크랩 버튼 위치 설정 => 구현 예정입니다.
=> [Feat] 위키 상세조회 기능 (#86)

frontend/src/components/Common/PaginationComponent.vue, frontend/src/components/Point/PointHistoryComponent.vue, frontend/src/components/Point/PointInfoComponent.vue, frontend/src/components/Point/PointRankingComponent.vue, frontend/src/components/Point/PointRankingUserComponent.vue, frontend/src/components/qna/QnaListCardComponent.vue, frontend/src/pages/PointPage.vue, frontend/src/router/index.js, frontend/src/store/usePointStore.js
close #72 
랭킹 조회 페이지 구현
랭킹 조회 API와 연결
페이징 처리
데이터는 신경 X
=> [Feat] 랭킹 조회 페이지 구현 (#72)

backend/src/main/java/org/example/backend/Common/UserGradeIconManager.java, backend/src/main/java/org/example/backend/Config/SecurityConfig.java, backend/src/main/java/org/example/backend/Point/Controller/PointController.java, backend/src/main/java/org/example/backend/Point/Model/Res/GetPointRankRes.java, backend/src/main/java/org/example/backend/Point/Service/PointService.java
close #69 
사용자로부터 page와 size를 받아 전체 유저의 랭킹 정보를 조회
point로 내림차순 정렬하여 조회
로그인한 사용자만 조회 가능
``` json
{
"code": 1000,
"result": [
{
"point": 25000,
"rank": 1,
"userId": null,
"nickname": "길동홍",
"profileImg": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/09/422ab83b-5d82-4e7a-9747-a26107603f6e",
"grade": "뉴비",
"gradeImg": "https://enadu.s3.ap-northeast-2.amazonaws.com/gradeicon/newbie.svg",
"totalPage": 1
},
{
"point": 25000,
"rank": 2,
"userId": null,
"nickname": "동홍길",
"profileImg": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/09/422ab83b-5d82-4e7a-9747-a26107603f6e",
"grade": "뉴비",
"gradeImg": "https://enadu.s3.ap-northeast-2.amazonaws.com/gradeicon/newbie.svg",
"totalPage": 1
},
{
"point": 2000,
"rank": 3,
"userId": …
```
=> [Feat] 전체 유저 랭킹 조회 API 구현 (#69)

frontend/src/router/index.js
=> [Fix] index.js오타 수정

frontend/package-lock.json, frontend/package.json, frontend/src/components/user/SignUpComponent.vue, frontend/src/pages/LoginPage.vue, frontend/src/store/useUserStore.js
close #187 
이메일, 닉네임 중복시 alert 띄움
중복이 아니여야 회원가입 가능
=> [Fix] 이메일, 닉네임 중복 기능 추가(#58)

backend/src/main/java/org/example/backend/Answer/Model/Entity/AnswerComment.java, backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, backend/src/main/java/org/example/backend/Qna/model/Entity/QnaBoard.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerCommentDetailListRes.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerDetailListRes.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetQnaListRes.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionDetailRes.java
close #37 
상세 조회 시 상위 댓글을 통해 그 id를 조회할 때 발생하는 null에 대한 접근 에러를 해결
=> [Fix] 댓글을 자기참조 null에 관한 에러처리

frontend/src/components/qna/QnaRegisterComponent.vue, frontend/src/store/useQnaStore.js
close #103 
카테고리 선택이 가능한 모달 페이지를 연결
등록 관련 에러 처리
=> [Fix] 질문 등록 과정 카테고리 선택 모달 추가 및 에러 처리

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java
close #1 
회원 가입시, 이메일 중복 확인, 닉네임 중복 확인 추가
=> [Fix] 회원가입시 이메일, 닉네임 중복(#1)

frontend/src/components/qna/QnaDetailComponent.vue, frontend/src/components/qna/QnaRegisterComponent.vue
close #100 
qna 상세조회 vm-editor 연결
=> [Feat] Qna 상세조회 vm-editor 뷰어 프로그램 연결

frontend/src/components/Chat/ChatComponent.vue, frontend/src/components/Chat/ChatNavComponent.vue, frontend/src/components/Chat/ChatRoomComponent.vue, frontend/src/pages/ChatPage.vue, frontend/src/store/useChatStore.js, frontend/src/store/useUserStore.js
close #200 
- 채팅 페이지 진입시 오류 나던 현상 해결
- 로그인한 사용자의 채팅방이 없을 경우 생기던 현상
- 받은 메세지가 여러번 출력되던 현상 해결
- 채팅방을 바꿨을 때 기존의 채팅방에 대한 구독을 끊지 않아서 생기던 문제
- 채팅방을 선택할 때 disconnect 함수를 호출하도록 변경
=> [Fix] 채팅 페이지 오류 해결 (#200)

frontend/src/components/Chat/ChatComponent.vue, frontend/src/components/Common/NicknameComponent.vue, frontend/src/router/index.js, frontend/src/store/useChatStore.js
close #206 
- 닉네임을 클릭했을 때 해당 유저에 회원 정보와, 1:1 채팅을 시작할 수 있는 dropbox가 나타난다.
- props로 nickname을 주면 된다.
- nickname의 글자 크기는 상위 컴포넌트에서 결정
- dropbox의 글자 크기는 nickname컴포넌트에서 결정되어 수정 안됌
사용법
예시 코드는 올라가지 않음
=> [Feat] Nickname 컴포넌트 구현 (#206)

frontend/src/components/Header/HeaderComponent.vue, frontend/src/components/Mypage/Info/InfoComponent.vue, frontend/src/components/Mypage/Info/PasswordModal.vue, frontend/src/components/Mypage/MypageComponent.vue, frontend/src/components/Mypage/ScrapListComponent.vue, frontend/src/components/Mypage/UserLogComponent.vue, frontend/src/pages/MypagePage.vue, frontend/src/router/index.js, frontend/src/store/useUserStore.js
close #70
- 마이페이지 상단 틀 추가
- 마이페이지 회원 정보 조회 추가
- 닉네임 변경, 프로필 이미지 변경, 비밀번호 변경(모달) 추가
=> [Feat] 회원 정보 페이지 추가(#70)

frontend/src/components/user/SignUpComponent.vue, frontend/src/store/useUserStore.js
close #1 
-  v-if="emailAvailable", v-if="nicknameAvailable" ,watch객체를 추가하여 특정 데이터 속성의 변경을 감지하여 자동으로 호출되는 메소드를 정의.
userInfo.email과 userInfo.nickname의 값이 변경될 때 중복 확인 상태를 초기화하기 위해 watch 객체 사용
- @input=validateEmail, @input=validateNickname 으로 이메일과 닉네임 입력시 공백이 들어가면 안되게끔 
- confirm으로 사용자가 회원가입을 진행하게끔 함
비밀번호도 공백 입력이 안되게끔 추가하겠습니다
=> [Feat] 회원가입시 이메일, 닉네임 중복 확인, 공백 확인

backend/hs_err_pid14324.log, backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java, backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiVersionDetailReq.java, backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiVersionDetailRes.java, backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #183 
📌위키 이전버전 상세 조회 API
- 사용자가 위키id, 버전 입력시 해당 버전 상세조회 가능
- 유저 정보에 따라 스크랩 여부 출력
- 제목, 내용, 카테고리, 버전, 스크랩 여부 출력
=> [Feat] 위키 이전버전 상세 조회 API (#183)

frontend/src/router/index.js
위키 등록 라우터 수정
{ path: "/wiki", component: WikiRegisterPage },
=>     { path: "/wiki/register", component: WikiRegisterPage },
=> [Fix] 위키 등록 라우터 수정

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue
- 에러아카이브 상세 조회 페이지에 목차 기능 구현
- 목차 클릭 시 해당하는 부분으로 이동
=> [Feat] 에러아카이브 상세 조회에 목차 기능 구현

backend/src/main/java/org/example/backend/Common/BaseResponse.java, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorArchive.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorLike.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorScrap.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Res/ToggleResponse.java, backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java, backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorLikeRepository.java, backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorScrapRepository.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
close #이슈번호
- 좋아요, 싫어요, 스크랩 메소드 추가
- 좋아요를 누른 상태에서 싫어요를 누르면, 좋아요수는 -1, 싫어요 수는 +1
- 싫어요를 누른 상태에서 좋아요를 누르면, 좋아요는 +1, 싫어요 수는 -1
- 좋아요 누르고 아무 동작 없으면 좋아요수 +1, 싫어요 수는 변화 없음
- 싫어요 누르고 아무 동작 없으면 싫어요 수+1, 좋아요 수는 변화 없음
- 스크랩한 상태에서 스크랩을 다시 하면, 스크랩이 취소됨
- 스크랩한 이후 아무 동작 없으면 스크랩 한 상태
=> [Feat] 에러 아카이브 좋아요/싫어요, 스크랩 추가

backend/src/main/java/org/example/backend/Wiki/Model/Res/WikiListRes.java, backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #26 
위키 목록 조회 Res에 totalPages 추가
=> [Fix] 위키 목록 조회 totalPages 추가 (#26)

frontend/src/components/wiki/WikiDetailComponent.vue, frontend/src/pages/WikiDetailPage.vue
- 위키 상세 페이지 완성도 높임
- 목차 생성
- css 수정
- 수정 버튼, 스크랩 버튼 오른쪽으로 이동
- 이전 버전 위키 버튼 추가
=> [Feat] 위키 상세 페이지 detail 작업

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Req/GetErrorArchiveSearchReq.java, backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/DbErrorArchiveSearchService.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveSearchService.java
close #13 
- 에러아카이브 검색 API 구현
- page, size (기본은 0, 16)
- sort (기본 'latest')
- keyword (기본은  '')
- type (기본 'tc')
- categoryId 
- keyword랑 categoryId가 둘다 비어서 요청이 오면 예외 요청이 비어있다는 예외 발생
- 둘중 하나만 있으면 각각 검색
- 둘다 있으면 둘 다로 검색
- keyword를 통해 검색할 때는 keyword를 lowercase로 변경하고, 문자열 양끝 공백을 모두 제거한 뒤 검색
``` json
{
"code": 1000,
"result": [
{
"id": 5,
"title": "에러 아카이브22",
"content": "# 에러아카이브\n\n## 에러아카이브\n\n- 에러아카이브1\n- 에러아카이브2\n- 에러아카이브3 \n\n\n![desc](https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/20/8a805220-59cf-4d49-b050-1416a500bdae){{{width=\"auto\" height=\"auto\"}}}",
"superCategory": "MYSQL",
"subCategory": "INDEX",
"likeCnt": 0,
"grade": "견습",
"createdAt": "2024-09-20T12:49:25.713707",
"nickname": "홍길동",
"profileImg": …
```
=> [Feat] 에러아카이브 검색 API 구현 (#13)

backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiVersionDetailRes.java, backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
=> [Fix] 위키 이전버전 상세조회 Response 수정

frontend/src/store/useWikiStore.js
=> [Fix] 컨플릭트 해결 후 에러 처리

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/Exception/custom/InvalidMypageException.java, backend/src/main/java/org/example/backend/Qna/Repository/QuestionRepository.java, backend/src/main/java/org/example/backend/User/Controller/MypageController.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java, backend/src/main/java/org/example/backend/User/Model/Res/GetUserQnaListRes.java, backend/src/main/java/org/example/backend/User/Service/MypageService.java, backend/src/main/java/org/example/backend/User/Service/UserService.java
close #28
- UserController, UserService에서 MypageController, MypageService로 분리
- 추후 유저 로그 페이지를 위해 본인꺼 조회 말고도 userId 같이 보낸다면 다른 사용자 작성내역 조회 가능
be-dev 브랜치 update 할 때 QuestionRepository 충돌날 수 있음
=> [Feat] 해당 사용자 질문 조회 (#28)

backend/src/main/java/org/example/backend/Qna/Repository/QuestionRepository.java, backend/src/main/java/org/example/backend/User/Controller/MypageController.java, backend/src/main/java/org/example/backend/User/Model/Res/GetQnaScrapListRes.java, backend/src/main/java/org/example/backend/User/Service/MypageService.java
close #30, #83
- 내가 작성한 답변 목록 조회
- QnA 스크랩한 목록 조회
=> [Feat] 답변 목록 조회, qna 스크랩 목록 조회 (#30, #83)

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/store/useErrorArchiveStore.js
에러아카이브 상세 조회 페이지 좋아요/싫어요, 스크랩 api 연결
- 로그인 안되있을 경우 스크랩, 좋아요/싫어요 컴포넌트 안보이도록 설정
=> [Feat] 에러아카이브 상세 조회 페이지 좋아요/싫어요, 스크랩 api 연결

backend/src/main/java/org/example/backend/Main/Controller/MainController.java, backend/src/main/java/org/example/backend/Main/Model/Res/MainRes.java, backend/src/main/java/org/example/backend/Main/Service/MainService.java
=> [Feat] 메인페이지 목록 조회 API 구현

frontend/src/router/index.js, frontend/src/store/useUserStore.js
- router에 중복 import제거
- useUserStore에 } 없던거랑 줄 맞춤 수정
=> [Fix] router랑 useUserStore 오타 수정

frontend/src/components/Category/SubCategoryModal.vue, frontend/src/components/Category/SuperCategoryModal.vue
=> [Fix] async 추가

frontend/src/pages/WikiVersionListPage.vue, frontend/src/store/useWikiStore.js
close #92 
📌 위키 롤백 기능 구현
- 위키 이전 버전 목록에서 롤백 버튼 추가
- 해당 버전의 롤백 버튼 클릭 시, 해당 버전이 최신 버전으로 업데이트 처리
- 롤백 시, confirm창으로 확인
- 롤백 성공 시, alert창으로 결과 출력
=> [Feat] 위키 롤백 기능 구현 (#92)

frontend/src/components/Common/PaginationComponent.vue, frontend/src/components/Mypage/History/HistoryListComponent.vue, frontend/src/components/Mypage/Scrap/ScrapListComponent.vue, frontend/src/components/wiki/WikiCardComponent.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/PointPage.vue, frontend/src/pages/QnaListPage.vue, frontend/src/pages/WikiListPage.vue, frontend/src/pages/WikiVersionListPage.vue, frontend/src/store/useMypageStore.js
close #80
- pagenation 컴포넌트 수정
- 위키 작성 목록 조회 추가
- 위키 카드, 메인 페이지 css 수정
=> [Feat] 위키 작성 목록 조회(#80)

frontend/src/components/wiki/WikiDetailComponent.vue, frontend/src/components/wiki/WikiVersionDetailComponent.vue, frontend/src/pages/WikiVersionListPage.vue, frontend/src/store/useWikiStore.js
close #94 
📌 위키 스크랩 기능 구현
- 유저가 원하는 버전의 위키를 스크랩 할 수 있음
- 비로그인 유저는 스크랩 버튼 비활성화 처리
- axios 연결
css도 추후에 이쁘게 꾸밀게 ^ㅡ^
=> [Feat] 위키 스크랩 기능 구현 (#94)

frontend/src/components/user/SignInComponent.vue, frontend/src/store/useChatStore.js, frontend/src/store/useQnaStore.js, frontend/src/store/useUserStore.js
=> [Fix] 백엔드 요청 주소 수정

cicd/front/Jenkinsfile, cicd/front/frontend-deployment.yaml, cicd/front/frontend-service.yaml, cicd/front/frontend.sh, cicd/front/nginx.conf, frontend/Dockerfile
- Jenkinsfile, Dockerfile 추가
- 실행할 deployment, service yaml 추가
- nignx 설정파일 추가
=> [Feat] cicd 프론트 초기 설정

cicd/back/Jenkinsfile
=> [Fix] Jenkinsfile 오타 수정

backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java, backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #265 #32 
- 스크랩 매개변수에 @RequestBody 추가
- 컨플릭트 해결 중 괄호 누락으로 인한 오류 해결
=> [Fix] 위키 스크랩 매개변수 어노테이션 수정 (#32)

cicd/back/Jenkinsfile
=> [Fix] Jenkinsfile Discord 설정 추가

backend/src/main/java/org/example/backend/Common/TestController.java
=> [Feat] TestController 추가

cicd/back/backend.sh
=> [Fix] backend.sh 수정

cicd/front/frontend-deployment.yaml, cicd/front/frontend.sh, frontend/nginx.conf
=> [Feat] ssl 설정

frontend/nginx.conf
=> [Feat] nginx.conf 수정

cicd/front/frontend-deployment.yaml, cicd/front/frontend-service.yaml
=> [Feat] 포트 수정

cicd/front/frontend-service.yaml, cicd/front/frontend.sh, frontend/Dockerfile, frontend/nginx.conf
=> [Fix] nginx 수정

frontend/src/components/wiki/WikiUpdateComponent.vue, frontend/src/pages/WikiListPage.vue
close #이슈번호
- 위키 updateComponent 이미지 업로드 기능 추가
=> [Fix] 위키 수정- 이미지 업로드 기능 추가

cicd/front/frontend-service.yaml, cicd/front/frontend.sh
=> [Fix] service yaml 수정

frontend/src/components/wiki/WikiRegisterComponent.vue, frontend/src/router/index.js
close #이슈번호
- 위키 등록시, 비로그인 유저 로그인 페이지로 리다이렉트 처리
=> [Fix] 위키 등록시 비로그인 유저 리다이렉트 처리

cicd/back/Jenkinsfile
=> [Fix] Jenkinsfile 수정

cicd/back/backend.sh
=> [Fix] 쉘 스크립트 수정

cicd/back/backend.sh
=> [Fix] 쉘 스크립트 color 수정

frontend/package.json
=> [Fix] 앱 이름 수정

cicd/back/backend.sh
=> [Fix] 쉘 스크립트 rollout 수정

cicd/back/backend-service.yaml
=> [Fix] backend-service color 수정

cicd/back/backend.sh
=> [Fix] 쉘 스크립트 공백 수정

cicd/back/kafka-deployment.yaml, cicd/back/zookeeper-deployment.yaml
=> [Feat] kafka-deployment, zookeeper-deployment 추가

backend/src/main/java/org/example/backend/Qna/Controller/AnswerController.java, backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerDetailListRes.java
=> [Fix] 컨트롤러 요청 형태 변경

frontend/nginx.conf
- nginx.conf 파일 수정
- 배포 404 에러 페이지 연결
=> [Feat] 배포 404 에러페이지 설정

backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorArchive.java, backend/src/main/java/org/example/backend/ErrorArchive/Model/Req/RemoveErrorArchiveReq.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
close #이슈번호
작성자만 해당 글을 삭제할 수 있음
삭제 성공(true), 삭제 실패(false)로 처리
=> [Feat] 에러 아카이브 삭제 api 구현

frontend/src/components/qna/QnaAnswerDetailComponent.vue, frontend/src/components/qna/QnaAnswerRegisterComponent.vue, frontend/src/components/qna/QnaDetailComponent.vue, frontend/src/store/useQnaStore.js
close #100
qna 답변 입력창이 버튼을 통해 생성되고 v-md에디터 형식으로 구현
입력된 값은 전송 버튼으로 데이터를 백엔드로 전송하거나, 취소가 가능하도록 구현
각 답변은 작성된 즉시, 바로 업데이트 되어 사용자에게 보여지도록 구현
=> [Feat] qna 답변 등록 구현

frontend/src/App.vue, frontend/src/components/Header/HeaderComponent.vue, frontend/src/components/Mypage/History/HistoryListComponent.vue, frontend/src/components/Mypage/Info/InfoComponent.vue, frontend/src/components/Mypage/Scrap/ScrapListComponent.vue, frontend/src/components/user/SignInComponent.vue, frontend/src/pages/LoginPage.vue, frontend/src/store/useMypageStore.js, frontend/src/store/useUserStore.js
close #76, #81
- 위키 스크랩 목록
- 에러 아카이브 작성내역 목록
- 에러 아카이브 스크랩 목록
- 로그아웃 reload 안 되는 부분 수정
- 전역 폰트 추가
- 로그인 부분에 로딩 컴포넌트 추가
=> [Feat] 아카이브 작성내역, 스크랩/위키 스크랩목록 조회 추가 (#76,#81,#104)

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/Qna/Controller/AnswerController.java, backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java, backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, backend/src/main/java/org/example/backend/Qna/model/Entity/Answer.java, backend/src/main/java/org/example/backend/Qna/model/Entity/QnaBoard.java, backend/src/main/java/org/example/backend/Qna/model/req/EditAnswerReq.java, backend/src/main/java/org/example/backend/Qna/model/req/EditQuestionReq.java
close #35 
질문 수정 메커니즘 구현 
- 작성된 답변이 없을 경우 수정 가능
답변 수정 메커니즘 구현
- 채택되지 않은 답변의 경우 수정 가능
관련 에러 처리
=> [Feat] qna 질문 및 답변 수정 api 

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java, backend/src/main/java/org/example/backend/Qna/Repository/QuestionRepository.java, backend/src/main/java/org/example/backend/User/Controller/MypageController.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java, backend/src/main/java/org/example/backend/User/Model/Res/GetLogUserInfoRes.java, backend/src/main/java/org/example/backend/User/Model/Res/GetUserArchiveListRes.java, backend/src/main/java/org/example/backend/User/Model/Res/GetUserWikiListRes.java, backend/src/main/java/org/example/backend/User/Repository/UserRepository.java, backend/src/main/java/org/example/backend/User/Service/MypageService.java, backend/src/main/java/org/example/backend/User/Service/UserService.java, backend/src/main/java/org/example/backend/Wiki/Repository/WikiContentRepository.java
close #24, #67
- 아카이브 작성 내역 조회
- 아카이브 스크랩 내역 조회
- 유저 로그에서 상단에 유저 정보 조회
- 게시글들 enabled가 true인 것만 조회
- pages에서 s 제거
=> [Feat ]아카이브 작성내역, 스크랩 조회 (#24, #67), 유저 로그 페이지 정보 조회 추가

backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerCommentDetailListRes.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerDetailListRes.java, backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionDetailRes.java
close #37 
상세 조회 api 응답 데이터 수정
=> [Fix] 상세 조회 api 응답 데이터 수정 

frontend/src/components/Common/PaginationComponent.vue
=> [Fix] pagination css 변경

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/components/errorarchive/ErrorArchiveRegisterComponent.vue, frontend/src/components/errorarchive/ErrorArchiveUpdateComponent.vue, frontend/src/components/user/SignUpComponent.vue, frontend/src/pages/ErrorArchiveUpdatePage.vue, frontend/src/router/index.js, frontend/src/store/useErrorArchiveStore.js, frontend/src/store/useUserStore.js
close #이슈번호
- 수정 페이지 구현
- 작성자만 본인이 쓴 게시글 수정하게끔 '버튼하기' 생성
수정 버튼 위치, 크기 등 수정
수정 페이지에서 상세 페이지 불러오게 기능 구현할 것
=> [Feat] 에러 아카이브 수정 페이지 구현, 작성자만 id만 수정하기 버 튼보이게 버튼  생성

frontend/src/components/user/SignUpComponent.vue, frontend/src/router/index.js
close #이슈번호
에러아카이브 수정 충돌 해결할 때 생긴 오류 해결
import문  errorarchiveupdate 추가
<div> 추가
=> [Fix] 에러아카이브 수정 충돌 해결할 때 생긴 오류 해결

frontend/src/pages/LoginPage.vue, frontend/src/store/useUserStore.js
close
- 소셜 로그인할 때 try-catch 추가
=> [Fix] try-catch로 json 응답 안 띄우기

backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java, backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
close #이슈번호
삭제한 글은 enable이 false가 되고 enable이 false인 글은 목록 페이지에서 보이지 않도록 함
=> [Fix] findByEnableTrue추가

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/pages/EmailVerifyPage.vue, frontend/src/pages/LoginPage.vue, frontend/src/router/index.js, frontend/src/store/useErrorArchiveStore.js
close #이슈번호
1. 회원가입 버튼을 누르면 이메일 인증 하라는 alert를 띄움
2. 이메일에 온 링크를 클릭하면 우리 페이지로 이동해서
3. 로그인 하러가기 버튼을 누르면 회원가입 성공
=> [Fix] 이메일 인증 후 회원가입 하게끔 수정

backend/src/main/java/org/example/backend/Security/OAuth2LoginFailureHandler.java
=> [Fix] failure handler 수정

frontend/src/pages/OAuthLoginPage.vue, frontend/src/store/useUserStore.js
=> [Fix] oauth 페이지 수정

backend/src/main/resources/application.yml, cicd/back/Jenkinsfile, cicd/back/backend-oauth-service.yaml, cicd/back/backend.sh
=> [Fix] oauth 서비스 추가

frontend/nginx.conf, frontend/src/store/useUserStore.js
=> [Fix] oauth 서비스 연결

frontend/src/components/Common/SearchComponent.vue, frontend/src/pages/ErrorArchiveListPage.vue
close #347 
- 검색 시 아무것도 선택 안하고 검색 안되도록 변경
=> [Feat] 아무것도 선택안하고 검색 안되도록 변경(#347)

backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java, backend/src/main/java/org/example/backend/ErrorArchive/Service/DbErrorArchiveSearchService.java
close #349 
- 에러아카이브 검색 n+1해결
- user에 대해서 n+1 발생
- fetch join을 사용해서 해결
``` java 
@Query("SELECT er FROM ErrorArchive er JOIN FETCH er.user WHERE (LOWER(er.title) LIKE CONCAT('%', :keyword,'%') " +
"OR LOWER(er.content) LIKE CONCAT('%', :keyword,'%')) AND er.category.id = :categoryId AND er.enable")
Page<ErrorArchive> findAllByKeywordAndCategory(String keyword, Long categoryId, Pageable pageable);
```
<details>
<summary>해결 전 쿼리</summary>
``` 
2024-09-28T17:44:08.645+09:00 DEBUG 13752 --- [nio-8080-exec-3] org.hibernate.SQL                        : 
select
c1_0.id,
c1_0.category_name,
sc1_0.id,
sc1_0.category_name,
sc1_0.super_category_id 
from
category c1_0 
left join
category sc1_0 
on sc1_0.id=c1_0.super_category_id 
where
c1_0.id=?
2024-09-28T17:44:08.645+09:00 TRACE 13752 --- …
```
=> [Refactor] 에러아카이브 검색 N+1 해결(#349)

frontend/src/pages/PointPage.vue
close #342 
- 포인트 페이지 tag추가
- 포인트 페이지에 페이지네이션 컴포넌트 이상하게 나오던거 정상적으로 나오게 해결
=> [Fix] 포인트페이지 페이지네이션 컴포넌트 이상하게 나온거 해결(#342)

backend/src/main/java/org/example/backend/Qna/Repository/AnswerLikeRepository.java, backend/src/main/java/org/example/backend/Qna/Repository/QnaLikeRepository.java, backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
close #43
삭제한 답변을 요청하는 방식 수정 
기존 getDetail에서 답변의 enable을 filtering하도록 변경
=> [Fix] Qna 답변 enable 처리에러 해결

backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java
close #352 
기존 코드에서 errorarchive.getContent()를 통해 errorarchive객체들을 가져온 후, 각 errorarchive에 대해 카테고리 정보를 
접근해서 추가 쿼리가 생겼음
`@Query("SELECT ea FROM ErrorArchive ea JOIN FETCH ea.user JOIN FETCH ea.category WHERE ea.enable = true")
Page<ErrorArchive> findByEnableTrue(Pageable pageable);
`
15개의 쿼리문에서 5개의 쿼리문으로 줄임
<details>
<summary>해결 전 쿼리</summary>
```
2024-09-28T21:04:56.113+09:00 DEBUG 20512 --- [nio-8080-exec-1] org.hibernate.SQL                        : 
select
ea1_0.id,
ea1_0.category_id,
ea1_0.content,
ea1_0.created_at,
ea1_0.enable,
ea1_0.hate_cnt,
ea1_0.like_cnt,
ea1_0.modified_at,
ea1_0.scrap_count,
ea1_0.title,
ea1_0.user_id 
from
error_archive ea1_0 
where
ea1_0.enable 
order by
ea1_0.created_at desc 
limit
?
2024-09-28T21:04:56.114+09:00  WARN 20512 --- [ntainer#0-0-C-1] …
```
=> [Refactor] 에러 아카이브 목록 조회 n+1문제

frontend/Dockerfile, frontend/src/components/Chat/ChatComponent.vue, frontend/src/components/Chat/ChatRoomComponent.vue, frontend/src/pages/ChatPage.vue, frontend/src/pages/OAuthLoginPage.vue, frontend/src/store/useChatStore.js, frontend/vue.config.js
close #340
- Dockerfile에 주석을 해제하여 img도 올라가도록 수정
- 자기 자신과 채팅방 안만들어지도록 수정
- 자신이 보낸 메세지가 두번씩 출력되던거 수정
- 채팅방을 너무 빠르게 선택하면 생기던 오류 해결
- 로딩 추가
- tag추가
=> [Fix] 채팅 관련 버그 해결 (#340)

backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java
close #349 
- 에러아카이브 검색 모든 조건에 대해서 N+1 해결
- 조건 모두 JPQL 사용
- category가 검색 조건에 포함되지 않을 경우 user, category, category.supercategory와 fetch join
- category가 검색 조건일 경우 user만 fetch join
<details>
<summary>1차 해결 후</summary>
```
2024-09-28T18:13:16.299+09:00 DEBUG 18236 --- [nio-8080-exec-9] org.hibernate.SQL                        : 
select
c1_0.id,
c1_0.category_name,
sc1_0.id,
sc1_0.category_name,
sc1_0.super_category_id 
from
category c1_0 
left join
category sc1_0 
on sc1_0.id=c1_0.super_category_id 
where
c1_0.id=?
2024-09-28T18:13:16.299+09:00 TRACE 18236 --- [nio-8080-exec-9] org.hibernate.orm.jdbc.bind              : binding parameter (1:BIGINT) <- [1]
2024-09-28T18:13:16.320+09:00 DEBUG 18236 --- [nio-8080-exec-9] org.hibernate.SQL                        : 
select
ea1_0.id, …
```
=> [Refactor] 에러아카이브 검색 모든 조건 N+1 해결(#349)

frontend/src/components/Common/SearchComponent.vue, frontend/src/pages/ErrorArchiveListPage.vue
close #353 
- 에러아카이브 검색 시 두번씩 api를 호출하던 현상 수정
=> [Fix] 에러아카이브 검색시 두번 api 호출 하던 현상 수정 (#353)

frontend/src/pages/WikiVersionListPage.vue, frontend/vue.config.js
close #363 
📌 위키 롤백 후 새로고침 방식 수정
- 기존 reload방식에서 스토어 메서드 호출 방식으로 변경
=> [Refactor] 위키 롤백후 새로고침 방식 수정 (#363)

frontend/src/pages/WikiVersionListPage.vue
close #362 
📌 위키 이전버전 목록 조회에 롤백 가능 등급 안내 추가
=> [Feat] 위키 이전버전 목록 - 롤백 가능 등급 추가 (#362)

frontend/src/components/Qna/Refactor/QnaAnswerEditComponent.vue
=> [Fix] Qna import 문제 해결

backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorArchiveReository.java, backend/src/main/java/org/example/backend/Qna/Repository/QuestionRepository.java, backend/src/main/java/org/example/backend/User/Service/MypageService.java, backend/src/main/java/org/example/backend/Wiki/Repository/WikiContentRepository.java
close #368
- 작성내역과 스크랩 부분 쿼리 최적화 (n+1 문제)
=> [Feat] 마이페이지 쿼리 최적화 (#368)

frontend/src/store/useWikiStore.js
close #384 
📌롤백 시, 권한 없는 유저 alert창 출력 처리
- 비로그인 유저, 뉴비 등급
=> [Feat] 롤백 시, 권한 없는 유저 alert창 출력 (#384)

backend/src/main/java/org/example/backend/Config/SecurityConfig.java, backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
=> [Refactor] 위키 시큐리티 인가 설정 (#388)

frontend/src/components/Mypage/History/HistoryListComponent.vue, frontend/src/components/Mypage/Log/UserLogComponent.vue, frontend/src/components/Mypage/Scrap/ScrapListComponent.vue, frontend/src/pages/ErrorArchiveListPage.vue, frontend/src/pages/WikiListPage.vue
close #382
- 위키 목록, 아카이브 목록, 내 스크랩 목록, 내가 쓴 글 목록, 유저 로그에 설정
=> [Fix] 페이지네이션 6페이지 이후도 나오게 수정 (#382)

frontend/src/components/Common/TagComponent.vue, frontend/src/pages/ChatPage.vue, frontend/src/pages/ErrorArchiveListPage.vue, frontend/src/pages/ErrorArchiveRegisterPage.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/MypagePage.vue, frontend/src/pages/PointPage.vue, frontend/src/pages/QnaListPage.vue, frontend/src/pages/UserLogPage.vue, frontend/src/pages/WikiListPage.vue
close #386 
- 메인페이지, 목록페이지, 마이페이지, 로그페이지, 채팅페이지, 포인트페이지 태그 위치 변경
=> [Refactor] 태그 컴포넌트 위치수정 (#386)

frontend/src/components/Common/AdditionalInfoComponent.vue, frontend/src/components/Common/PaginationComponent.vue, frontend/src/components/Common/SearchComponent.vue, frontend/src/components/Header/HeaderComponent.vue, frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/components/Qna/List/QnaListCardComponent.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/QnaListPage.vue, frontend/src/store/useMainStore.js, frontend/src/store/useQnaStore.js
close #133 
비로그인 사용 자의 접근 권한 부여 (채택, 등록, 좋아요 scrap 제외 단순 조회 기능)
qna 목록 및 검색 시 pagination 컴포넌트를 통한 페이징 구현
질문 및 답변의 좋아요 및 싫어요와 그 수 및 질문의 스크랩 여부를 조회하는 메커니즘 구현
조회 api axios 연결 및 에러 처리
=> [Fix] qna에 비로그인 사용자의 접근 권한 범위 지정 및 좋아요 및 스크랩 조회 메커니즘 구현

backend/src/main/java/org/example/backend/Config/SecurityConfig.java
close #393 
인가되지 않은 사용자 security로 설정
=> [Refactor] 인가 되지 않은 사용자 security로 설정 (#393)

frontend/src/components/errorarchive/ErrorArchiveRegisterComponent.vue, frontend/src/pages/LoginPage.vue, frontend/src/pages/MainPage.vue, frontend/src/store/useErrorArchiveStore.js
close #390 
- 에러아카이브 등록시 상세 페이지로 이동하게 설정
- 회원가입시 메인페이지로 이동하게 설정
=> [Feat] 회원가입, 에러아카이브 등록 router 설정 (#390)

frontend/src/components/Common/PaginationComponent.vue, frontend/src/components/Header/HeaderComponent.vue, frontend/src/components/Mypage/Scrap/ScrapListComponent.vue, frontend/src/components/user/OverlayComponent.vue, frontend/src/pages/MainPage.vue
- pagination 수정
- 로고 추가
- 스크랩 목록 기본값 변경
=> [Design] pagination css 수정, logo 추가

frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/pages/QnaDetailPage.vue, frontend/src/store/useQnaStore.js
close #133 
Qna Detail 정렬 및 제목의 길이 제한 후 ... 처리 진행
답변 및 질문 실제 글 백그라운드 CSS 수정
=> [Design] QnaCard 및 Detail css 수정

frontend/src/store/useQnaStore.js
close #301 
QnaSearch 에러처러 메시지 수정
=> [Fix] QnaSearch 에러처러 메시지 수정

frontend/src/store/useErrorArchiveStore.js
close #390 
- 에러아카이브 등록시 router 설정 fix
=> [Fix] 에러아카이브 등록 router 설정 fix (#390)

frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue
close #133 
로그인한 사용자에게만 좋아요 및 스크랩 버튼 시각화
=> [Fix] 로그인하지 않은 사용자에 대한 qna 상세조회에서의 처리 방식 변경

frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaCommentDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/components/Qna/Register/QnaAnswerRegisterComponent.vue, frontend/src/components/Qna/Register/QnaCommentRegisterComponent.vue
close #286 
답변 등록 시, 작성 컴포넌트 블라인드 설정
댓글 등록시, 작성 컴포넌트 블라인드 설정 및 리스트 컴포넌트 시각화
좋아요 및 스크랩 버튼 순서 수정
=> [Fix] 답변 및 댓글 등록 시, 등록 컴포넌트 및 리스트 컴포넌트 시각화 여부 변경 

frontend/src/App.vue, frontend/src/components/Category/SubCategoryModal.vue, frontend/src/components/Category/SuperCategoryModal.vue, frontend/src/components/Common/CategoryComponent.vue, frontend/src/components/Common/SearchComponent.vue, frontend/src/components/Mypage/History/HistoryListComponent.vue, frontend/src/components/Mypage/Log/UserLogComponent.vue, frontend/src/components/Mypage/Scrap/ScrapListComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/components/Qna/List/QnaListCardComponent.vue, frontend/src/components/Qna/Refactor/QnaEditComponent.vue, frontend/src/components/Qna/Register/QnaRegisterComponent.vue, frontend/src/components/errorarchive/ErrorArchiveCardComponent.vue, frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/components/wiki/WikiCardComponent.vue, frontend/src/components/wiki/WikiDetailComponent.vue, frontend/src/components/wiki/WikiVersionDetailComponent.vue, frontend/src/pages/ErrorArchiveListPage.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/QnaDetailPage.vue, frontend/src/pages/QnaListPage.vue, frontend/src/pages/WikiVersionListPage.vue
=> [Design] css 수정

backend/src/main/java/org/example/backend/Point/Model/Res/GetMyRankRes.java, backend/src/main/java/org/example/backend/Point/Model/Res/GetPointRankRes.java, backend/src/main/java/org/example/backend/Point/Service/PointService.java
=> [Fix] 포인트 관련 dto 수정

frontend/src/components/Mypage/Info/InfoComponent.vue, frontend/src/components/user/SignUpComponent.vue, frontend/src/store/useUserStore.js
=> [Feat] 소셜 유저 회원 탈퇴 (#327), 회원가입 로직 추가

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/Security/CustomOAuth2User.java, backend/src/main/java/org/example/backend/Security/CustomOAuth2UserService.java, backend/src/main/java/org/example/backend/Security/OAuth2LoginSuccessHandler.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java, backend/src/main/java/org/example/backend/User/Service/UserService.java, backend/src/main/java/org/example/backend/Util/JwtUtil.java
close #326
- 소셜 유저 회원 탈퇴 추가
- 회원 가입 시 요청 값 검증
=> [Feat] 소셜 유저 회원 탈퇴(#326)

frontend/package-lock.json, frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/store/useQnaStore.js
close #295 
답변과 질문에서 좋아요 상태로 싫어요를 하거나, 싫어요 상태로 좋아요를 했을때 처리 메커니즘 구현
좋아요와 싫어요의 axios response 수정
=> [Fix] 좋아요 및 싫어요 메커니즘 수정 완료

frontend/src/pages/QnaDetailPage.vue, frontend/src/store/useQnaStore.js
=> [Fix] 불필요할 alert 제거

frontend/src/components/Common/TagComponent.vue, frontend/src/pages/MainPage.vue
=> [Design] 태그 컴포넌트 배경색깔 지정

frontend/src/components/Common/SearchComponent.vue
=> [Design] 검색 컴포넌트 색상 변경

backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/User/Controller/UserController.java
=> [Fix] 회원가입 예외처리 수정 (#419)

backend/build.gradle, backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, backend/src/main/java/org/example/backend/Config/QuerydslConfig.java, backend/src/main/java/org/example/backend/Qna/Repository/QnaRepositoryCustom.java, backend/src/main/java/org/example/backend/Qna/Repository/QnaRepositoryCustomImpl.java, backend/src/main/java/org/example/backend/Qna/Service/BasicQnaSearchService.java, backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, backend/src/main/java/org/example/backend/Qna/model/Entity/QnaBoard.java
close #301 
- 상위 카테고리만 선택하거나, 카테고리를 선택하지 않아도 검색 가능
build gradle queryDSL import
qna 검색 queryDSL 적용
- 공백 및 대소문자 상관 없이 검색
- 카테고리 및 키워드 미 입력시 검색 조건에서 제외
- 검색 중 이미지의 주소 들어가는 경우 제외 -> 될때 있고 안될때 있음...
=> [Feat] Qna 검색 QueryDSL을 활용한 동적 쿼리로 개선

backend/src/main/java/org/example/backend/Point/Aop/PointAop.java, backend/src/main/java/org/example/backend/Point/Model/Enum/PointDescriptionEnum.java, backend/src/main/java/org/example/backend/Point/Service/PointService.java
close #423 
- 위키 수정, 답변 작성, 답변 채택, 에러아카이브 추천/비추천, 답변 추천/비추천 포인트 부여/차감
- 추천/비추천은 해당 메서드가 실행되기 전에 추천수와 비추천 수를 ThreadLocal에 저장해 둔 다음에 AfterReturning 했을 때 변경 된 값으로 포인트 부여 및 차감
- ThreadLocal은 해당 스레드에서만 적용되는 변수. 만약 이걸 안쓰고 그냥 변수를 사용하면 다른 스레드에서 접근이 가능해 코드가 꼬임
=> [Feat] 포인트 부여/차감 로직 완성 (#423)

frontend/src/components/wiki/WikiVersionDetailComponent.vue
close #246 
이전버전 상세조회 시, 버전 부분 커서 css효과 삭제
=> [Fix] 위키 이전버전 상세 css효과 수정

back/batch/src/main/java/com/example/batch/BatchApplication.java, back/batch/src/main/java/com/example/batch/config/DataSourceConfig.java, back/batch/src/main/resources/application.yml
- 데이터베이스 분리를 위한 DataSourceConfig 추가
=> [Feat] DataSourceConfig 추가

frontend/src/components/Common/AdditionalInfoComponent.vue, frontend/src/components/Common/SearchComponent.vue, frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailComponent.vue, frontend/src/components/Qna/Register/QnaRegisterComponent.vue, frontend/src/pages/QnaDetailPage.vue, frontend/src/pages/QnaListPage.vue, frontend/src/store/useQnaStore.js
close #418
- 채택 권한 확인 과정 추가
- 수정 및 삭제 버튼 권한 확인하고 가시 여부 결정 
- qnaStore 연결 부분 리팩토링중 (조회 부분 완료)
=> [Fix] Qna 권한에 따른 처리 변경

back/backend/build.gradle, back/build.gradle
=> [Feat] Elastic-Search 라이브러리 위치 수정

back/backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, back/backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #441 
📌뉴비 등급 유저 등록 제한 처리
=> [Feat] 위키 등록 권한 제한 (#441)

frontend/src/pages/WikiListPage.vue, frontend/src/router/index.js, frontend/src/store/useWikiStore.js
close #439
📌위키 등록 시 뉴비등급 유저, 비로그인 유저 등록 권한 제한 처리
📌비로그인 유저 URL로 등록 페이지 요청시, 로그인페이지로 리다이렉트 처리
=> [Feat] 위키 등록 권한 제한 (#439)

back/backend/build.gradle, back/backend/docker-compose.yml, back/backend/src/main/java/org/example/backend/BackendApplication.java, back/backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java, back/backend/src/main/java/org/example/backend/Qna/Repository/ElasticsearchQuestionRepository.java, back/backend/src/main/java/org/example/backend/Qna/Service/ElasticQnaSearchService.java, back/backend/src/main/java/org/example/backend/Qna/model/Doc/QnaBoard.java, back/backend/src/main/resources/application.yml, back/build.gradle
=> Revert의 Revert [Feat] Elasticsearch 라이브러리 설정 및 테스트 (#443)

back/backend/src/main/java/org/example/backend/Config/ElasticSearchConfig.java, back/backend/src/main/resources/application.yml
=> [Feat] Elasticsearch config파일 생성

frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue
=> [Feat] ai 답변 추가

back/backend/src/main/java/org/example/backend/Point/Service/PointService.java, back/batch/src/main/java/com/example/batch/config/BatchDataSourceConfig.java, back/batch/src/main/java/com/example/batch/config/MainDataSourceConfig.java, back/batch/src/main/java/com/example/batch/job/BatchJobRunner.java, back/batch/src/main/java/com/example/batch/job/DailyRankJob.java, back/batch/src/main/resources/application.yml, back/common/src/main/java/com/example/common/Ranking/Repository/RankRepository.java, back/common/src/main/java/com/example/common/Ranking/Service/RankService.java, back/common/src/main/java/com/example/common/Ranking/model/Entity/Ranking.java, back/common/src/main/java/com/example/common/User/Model/Entity/User.java, back/common/src/main/java/com/example/common/User/Repository/UserRepository.java
close #446
- spring 배치 관련 implement 및 yml 설정
- 스프링 배치 DB 및 기본 백엔드 서비스 DB config
- job과 step 메커니즘 구현
- 랭킹 엔티티 생성
=> [Feat] 스프링 배치를 활용한 user 랭킹 시스템 구현

frontend/src/components/Common/CategoryComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/components/Qna/QnaResolvedComponent.vue, frontend/src/components/Qna/Register/QnaRegisterComponent.vue, frontend/src/pages/QnaDetailPage.vue, frontend/src/pages/QnaListPage.vue, frontend/src/store/useQnaStore.js
close #462 
qna 등록 카테고리 관련 문제 해결
검색 과정에서 정렬 메커니즘 및 페이지네이션에서 발생하는 문제 해결
=> [Fix] qna 등록 에러 해결 및 검색 메커니즘 수정

frontend/src/components/Qna/QnaResolvedComponent.vue, frontend/src/pages/QnaListPage.vue, frontend/src/store/useQnaStore.js
close #451
답변의 채택 여부 확인을 통한 qna 해결 및 미해결 여부 판단
해결, 미해결, 전체 조회 컴포넌트 구현
검색 및 조회 과정에서 해결 및 미 해결 상태 변경 가능하도록 axios 변경
=> [Feat] qna 답변의 채택 여부를 확인하여 질문의 미해결 및 해결 여부 판단 메커니즘 구현  

back/backend/src/main/java/org/example/backend/Qna/Service/BasicQnaSearchService.java, back/backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, back/backend/src/main/java/org/example/backend/Qna/model/req/GetQnaListReq.java, back/backend/src/main/java/org/example/backend/Qna/model/req/GetQnaSearchReq.java, back/common/src/main/java/com/example/common/Qna/Repository/QnaRepositoryCustom.java, back/common/src/main/java/com/example/common/Qna/Repository/QnaRepositoryCustomImpl.java, back/common/src/main/java/com/example/common/Qna/model/Entity/QnaBoard.java, back/common/src/main/java/com/example/common/Qna/model/Resolved.java
close #301 
등록 기능 중 카테고리 선택 관련 에러 처리
querydsl 검색 기능에서 정렬 기준 적용에서 발생한 에러 해결
totalpage 리턴 에러 해결  
=> [Fix] qna 등록 및 검색 기능 에러 해결

back/backend/src/main/java/org/example/backend/Chat/Service/ChatService.java, back/backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, back/common/src/main/java/com/example/common/User/Repository/UserRepository.java
close #458 
- 자신과 채팅 안되도록 수정
- 분명 예전에 했는데.... 억울해
=> [Fix] 자신과 채팅 안되도록 수정 (#458)

frontend/src/store/useQnaStore.js
close #468 
qna 검색 및 목록 조회 시 데이터가 없을 경우 데이터 처리에 생기는 오류 해결
=> [Fix] qna 검색 및 목록조회 데이터가 없을 시 페이징 처리 에러 발생 해결

back/batch/src/main/java/com/example/batch/job/DailyRankingConfig.java, back/batch/src/main/java/com/example/batch/job/UnansweredConfig.java, back/batch/src/main/java/com/example/batch/job/WeeklyRankConfig.java, back/batch/src/main/java/com/example/batch/processor/AiAnswerProcessor.java, back/common/src/main/java/com/example/common/CommonApplication.java, back/common/src/main/java/com/example/common/Qna/Repository/QuestionRepository.java, back/common/src/main/java/com/example/common/Ranking/Repository/DailyRankingRepository.java, back/common/src/main/java/com/example/common/Ranking/Repository/RankRepository.java, back/common/src/main/java/com/example/common/Ranking/Repository/WeeklyRankingRepository.java, back/common/src/main/java/com/example/common/Ranking/Service/RankService.java, back/common/src/main/java/com/example/common/Ranking/model/Entity/DailyRanking.java, back/common/src/main/java/com/example/common/Ranking/model/Entity/WeeklyRanking.java, back/common/src/main/java/com/example/common/User/Model/Entity/User.java
- 랭킹 테이블 일간과 주간으로 분리 + 유저와 연관관계 추가
- 한국 시간대로 수정
- ai 요청 한국어로 고정
- 답변 안 달린 질문글 조회 조건 추가
=> [Feat] 랭킹 테이블 분리 및 추가

cicd/batch/Jenkinsfile, cicd/batch/batch-aianswer-cronjob.yaml, cicd/batch/batch-dailyRanking-cronjob.yaml, cicd/batch/batch-unanswered-cronjob.yaml
=> [Feat] jenkins batch 추가

back/backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveElasticSearchService.java
- 에러아카이브 검색 안되던 버그수정
- minimunshouldmatch 적용
=> [Fix] errorarchive 검색 버그 수정

back/backend/src/main/java/org/example/backend/Config/SecurityConfig.java, back/backend/src/main/java/org/example/backend/Point/Controller/PointController.java, back/backend/src/main/java/org/example/backend/Point/Model/Res/GetMyRankRes.java, back/backend/src/main/java/org/example/backend/Point/Model/Res/GetRankingRes.java, back/backend/src/main/java/org/example/backend/Point/Service/PointService.java, back/common/src/main/java/com/example/common/Ranking/Repository/DailyRankingRepository.java, back/common/src/main/java/com/example/common/Ranking/Repository/WeeklyRankingRepository.java, back/common/src/main/java/com/example/common/User/Model/Entity/User.java
close #479
- 일간, 주간 랭킹 api 추가
- 내 랭킹 조회 수정
- security에 ranking 부분 접근 권한 허용
=> [Feat] 일간, 주간 랭킹 api 추가 (#479)

back/backend/docker-compose.yml, back/backend/elasticsearch/config/index-settings.json
close #488 
- jaso analyzer 도입
=> [Feat] 엘라스틱 서치 jaso_analyzer 도입 (#488)

cicd/batch/Jenkinsfile, cicd/batch/batch-dailyranking-cronjob.yaml, cicd/batch/batch-unanswered-cronjob.yaml, cicd/batch/batch-weeklyranking-cronjob.yaml
close #485 
주간 랭킹 배치 크론잡 구현
젠킨스 파일에 주간 랭킹 크론잡 연결 추가
=> [CICD] 주간 랭킹 배치 크론잡 구현

cicd/batch/batch-weeklyranking-cronjob.yaml
=> [CICD] 주간 랭킹 배치 크론잡 수정

back/backend/src/main/java/org/example/backend/Main/Service/MainService.java, back/common/src/main/java/com/example/common/Qna/Repository/QuestionRepository.java
close #243 
Qna resolved데이터가 ended일때, 메인페이지에서 볼 수 없도록 쿼리 수정
=> [Feat] 메인 페이지에서의 qna resolved 적용

frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Register/QnaAnswerRegisterComponent.vue, frontend/src/components/Qna/Register/QnaRegisterComponent.vue, frontend/src/pages/QnaDetailPage.vue, frontend/src/pages/QnaListPage.vue
close #133 #34 
2주간 답변이 달리지 않은 질문글에 대한 안내메시지 추가
답변 등록 후 isLoading 추가
=> [Fix] ended 전환 안내 메시지 및 답변 작성 isLoading 추가

frontend/src/pages/RankingPage.vue
=> [Fix] 랭킹 데이터 에러 메시지 수정

back/backend/build.gradle, back/batch/build.gradle, cicd/back/Jenkinsfile
=> [Feat] 젠킨스에서 테스트 결과 확인 추가

frontend/nginx.conf
=> [Feat] 백엔드 에러페이지 처리 추가

cicd/back/Jenkinsfile, cicd/batch/Jenkinsfile
=> [Fix] return으로 파이프라인 조기 종료 수정

back/backend/elasticsearch/config/index-settings.json, back/backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java, back/backend/src/main/java/org/example/backend/Common/ChosungChecker.java, back/backend/src/main/java/org/example/backend/Wiki/Service/ElasticWikiSearchService.java
close #490
📌위키 초성검색 적용
- isChosungOnly 메서드 사용해서 초성 여부 확인
- 초성으로 한 글자 검색시 예외처리(두 글자부터 검색 가능)
=> [Feat] 위키 초성검색 적용

cicd/back/Jenkinsfile, cicd/back/backend-deployment.yaml, cicd/batch/Jenkinsfile
=> [Fix] 파이프라인 조기 종료 수정

frontend/src/components/Common/WikiSearchComponent .vue, frontend/src/pages/WikiListPage.vue
close #511 
📌초성 한글자 검색시 예외처리
- ALERT창 띄워주고 api요청 보내지않음
=> [Feat] 위키 초성 한글자 검색시 예외처리 (#511)

back/backend/src/main/java/org/example/backend/BackendApplication.java, back/backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java, back/backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, back/backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionEditDetailRes.java
close #313 
수정 조회 방식을 전체 조회가 아닌, 필요 데이터 조회 방식으로 개선
유저의 수정 권한 및 존재 id 여부 확인 메커니즘 구현
=> [Feat] Qna 수정 조회 api 개발

cicd/back/Jenkinsfile, cicd/batch/Jenkinsfile, cicd/batch/batch-aianswer-cronjob.yaml
=> [Fix] cicd 수정

frontend/src/components/wiki/WikiUpdateComponent.vue
close #518
📌위키 수정페이지 제목, 카테고리 박스 사이즈 수정
=> [Fix] 수정페이지- CSS 수정

frontend/src/pages/QnaListPage.vue
close #515 
- 한 글자 초성 검색시 alert창 띄우고 검색 안되도록 수정
=> [Feat] QnA 한글자 초성 검색시 예외처리(#515)

back/batch/Dockerfile, back/batch/src/main/java/com/example/batch/job/AiAnswerConfig.java, back/batch/src/main/java/com/example/batch/job/UnansweredConfig.java, back/batch/src/main/java/com/example/batch/processor/AiAnswerProcessor.java, back/batch/src/main/java/com/example/batch/writer/AnswerWriter.java, back/common/src/main/java/com/example/common/Qna/Repository/QuestionRepository.java, cicd/batch/batch-aianswer-cronjob.yaml, cicd/batch/batch-dailyranking-cronjob.yaml, cicd/batch/batch-unanswered-cronjob.yaml, cicd/batch/batch-weeklyranking-cronjob.yaml
=> [Fix] page 말고 list로 데이터 호출

back/backend/src/main/java/org/example/backend/File/Service/CloudFileUploadService.java
=> [Refactor] 위키 기본 이미지 변경 및 추가

frontend/src/pages/ErrorArchiveListPage.vue
close #이슈번호
- 한 글자 초성 검색시 alert창 띄우고 검색 안되도록 수정
=> [Feat] 에러아카이브 초성 예외 alert 처리

frontend/src/components/Header/HeaderComponent.vue, frontend/src/pages/MainPage.vue, frontend/src/pages/TotalSearchPage.vue, frontend/src/store/useMainStore.js
close #514
한 글자 초성 검색시 alert창 띄우고 검색 안되도록 수정
=> [Feat] 통합 검색 초성 예외처리(#514)

frontend/babel.config.js, frontend/jest.config.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/Qna/Refactor/QnaEditComponent.vue, frontend/src/pages/QnaDetailPage.vue, frontend/src/pages/RankingPage.vue, frontend/src/store/useQnaStore.js
close #313 
qna 수정 조회 axios 연결
router.push를 통한 404페이지 연결
하나만 있는 카테고리가 sub에 나오는 에러 수정
=> [Feat] Qna 수정 및 상세조회 컴포넌트 에러 처리

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/components/user/SignUpComponent.vue, frontend/src/pages/ErrorArchiveListPage.vue, frontend/src/store/useErrorArchiveStore.js
close #544 
- 세션 스토리지 수정해서 로그인 상태로 만든 후 에러아카이브 좋아요,싫어요, 스크랩 했을 때 alert창 띄우도록 설정
- signup 컴포넌트에 isValidEmail메서드 추가
- errorarchive 목록 컴포넌트에서 url로 검색 시 발생하는 문제들 수정
=> [Fix] 에러아카이브 관련 에러 수정 (#544)

back/backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiSearchReq.java, back/backend/src/main/java/org/example/backend/Wiki/Service/ElasticWikiSearchService.java
=> [Feat] 위키 검색 정렬 조건 추가 (#556)

back/backend/src/main/java/org/example/backend/Config/SecurityConfig.java, back/backend/src/main/java/org/example/backend/User/Controller/UserController.java, back/backend/src/main/java/org/example/backend/User/Model/Res/GetUserStatusRes.java
close #552 
close #551 
- 소셜 로그인 세션id 사용안하도록 변경
- 로그인 상태 확인 api 구현
=> [Feat] 소셜 로그인 세션id 사용X, 로그인 상태 확인 API

frontend/src/App.vue, frontend/src/components/Common/NicknameComponent.vue, frontend/src/pages/ChatPage.vue, frontend/src/store/useUserStore.js
close #533 
- 로그인 안한 유저 1:1 채팅 버튼 안보이도록 수정
=> [Feat] 로그인 안한 유저 1:1채팅 버튼 안보이도록 수정 (533)

frontend/src/components/user/SignUpComponent.vue
close #550 
- 회원가입시 닉네임이 50글자이상이면 alert띄우고 reset 처리
=> [Fix] 회원가입시 닉네임이 50글자이상이면 alert띄우고 reset(#550)

frontend/src/components/wiki/WikiDetailComponent.vue, frontend/src/components/wiki/WikiUpdateComponent.vue, frontend/src/components/wiki/WikiVersionDetailComponent.vue, frontend/src/pages/WikiVersionListPage.vue, frontend/src/router/index.js, frontend/src/store/useWikiStore.js
close #532 
📌위키 없는 URL id 예외처리
- 위키 상세조회
- 위키 이전버전 상세조회
- 위키 이전버전 목록조회
- 위키 수정 페이지
=> 위키 목록으로 리다이렉트 처리
📌위키 등록페이지 URL에 뭐든 추가로 입력시 예외처리
=> "?"기준으로 다 제거 처리
=> [Refactor] 위키 없는 URL id 예외처리 (#532)

frontend/src/components/Common/AdditionalInfoComponent.vue, frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Detail/QnaCommentDetailComponent.vue, frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue, frontend/src/components/Qna/Refactor/QnaEditComponent.vue
close #286 
로그인하지 않은 사용자의 댓글 대댓글 보기 권한 부여 및 작성 권한 조정
=> [Fix] 로그인 하지 않은 사용자의 댓글 보기 권한 수정

frontend/src/components/Common/AdditionalInfoComponent.vue, frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue, frontend/src/components/Qna/Refactor/QnaEditComponent.vue
close #448 
수정 권한이 없는 사용자의 수정 사이트 접속 에러 처리
수정 권한이 있지만, 수정 요건을 만족하지 않는 질문 글에 url을 통한 수정 페이지 접근에 대한 에러 처리
수정 및 삭제 조건에 ai 답변만 있는 case를 제외
ai 답변에 대한 좋아요 및 싫어요/ 댓글 기능 비활성화
=> [Feat] qna ai 답변에 대한 수정/삭제/채택/좋아요 권한 처리

cicd/front/frontend-deployment.yaml, frontend/src/components/Qna/List/QnaListCardComponent.vue, frontend/src/components/wiki/WikiRegisterComponent.vue, frontend/src/components/wiki/WikiUpdateComponent.vue, frontend/src/pages/WikiVersionListPage.vue, frontend/src/router/index.js, frontend/src/store/useMypageStore.js, frontend/src/store/useWikiStore.js
close #562, #565
- 견습 미만 위키 작성, 수정 접근 제한
- 라우처 로그인 필요한 페이지 검증 추가
- qna 카드 닉네임 길이 제한
- 위키 수정자 닉네임 길이 제한
- 마이페이지 아카이브 page size 변경
- nginx.confg 추가 방식 변경
=> [Feat] 프론트 수정

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/store/useErrorArchiveStore.js
close #546 
상세페이지에서 유효하지 않는 url입력시 에러 처리
=> [Feat] 상세페이지에서 유효하지 않는 url입력시 에러 처리(#546)

back/backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
close #이슈번호
userid를 안받아오고 있는거 수정
=> [Fix] 에러아카이브 edit-detail 메소드 수정

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/components/errorarchive/ErrorArchiveUpdateComponent.vue, frontend/src/pages/ErrorArchiveUpdatePage.vue, frontend/src/store/useErrorArchiveStore.js
close #526 
- 본인이 작성한 글을 url로 수정 페이지 이동 못하게끔 추가
- 본인이 작성한 글은 수정가능하게끔
=> [Feat] 본인이 작성하지 않은 글을 url로 수정페이지 못들어가게끔 추가(#526)

frontend/src/pages/ErrorArchiveUpdatePage.vue, frontend/src/pages/LoginPage.vue, frontend/src/store/useErrorArchiveStore.js, frontend/src/store/useUserStore.js
close #이슈번호
- 에러아카이브 수정페이지에서 유효하지 않는 url입력
- 권한이 없을때 url입력시 에러처리
=> [Fix] 에러아카이브 수정페이지에서 유효하지 않는 url입력, 권한이 없을때 url입력시 에러처리

frontend/src/components/Mypage/Info/InfoComponent.vue, frontend/src/components/user/SignUpComponent.vue, frontend/src/store/useMypageStore.js, frontend/src/store/useUserStore.js
- 닉네임, 이메일 중복 확인 관련 응답 처리 수정
- mypageStore 응답 처리 수정
=> [Fix] 중복 확인 수정

frontend/src/components/wiki/WikiUpdateComponent.vue
close #578 
📌위키 수정시, fetchUserDetails 호출하여 grade 정보 불러옴
=> [Fix] 위키 수정 컴포넌트 - 등급 오류 수정 (#578)

frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue, frontend/src/store/useErrorArchiveStore.js
=> [Fix] 에러아카이브 스크랩 버그 수정 (#580)

back/batch/src/main/java/com/example/batch/job/UnansweredConfig.java, back/common/src/main/java/com/example/common/Qna/Repository/QuestionRepository.java
close #582
- unanswered 배치 기준 수정
=> [Fix] unanswered 기준 수정 (#582)

frontend/src/pages/ErrorArchiveUpdatePage.vue, frontend/src/store/useErrorArchiveStore.js
close #584
- 아카이브 수정 페이지 접근할 때 권한 확인해서 막는 부분 수정
=> [Fix] 아카이브 수정 페이지 접근 권한 수정 (#584)

frontend/src/components/Qna/Register/QnaRegisterComponent.vue, frontend/src/store/useQnaStore.js
close #586
- qna 등록시 id 값 전달이 페이지쪽에 안 되어서 리다이렉트 안 되면서 400 에러
=> [Fix] qna 등록 시 리다이렉트 수정 (#586)

frontend/src/pages/QnaListPage.vue, frontend/src/pages/RankingPage.vue
close #588 
- 랭킹, QnA 목록 페이지 페이지네이션수정
- qna 정렬 선택 시 페이지네이션 초기화
=> [Fix] QnA, 랭킹 페이지네이션 버그 수정

back/backend/src/main/java/org/example/backend/Config/Filter/LoginFilter.java, back/backend/src/main/java/org/example/backend/Config/SecurityConfig.java, back/backend/src/main/java/org/example/backend/Exception/CustomAuthenticationFailureHandler.java, back/backend/src/main/java/org/example/backend/User/Service/MypageService.java
close #592
- 로그인 예외처리 관련 핸들러 추가
=> [Fix] 로그인 예외처리 수정 (#592)

back/backend/src/main/java/org/example/backend/Qna/Service/QnaService.java, back/backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionDetailRes.java
close #이슈번호
- edit-detail api에서 수정할 수 있는 질문글인지 확인
=> [Fix] qna 수정 권한 확인

frontend/src/components/Qna/Refactor/QnaEditComponent.vue, frontend/src/store/useQnaStore.js
close #이슈번호
- 수정 component에서 edit-detail api로 수정할 수 있는 게시글인지 확인 후 예외 처리
=> [Fix] QnA 수정 권한 버그 수정

back/common/src/main/java/com/example/common/Category/Model/Entity/Category.java
close #이슈번호
카테고리 생성되도록 id에 generatedValue 추가
=> [Fix] 카테고리 엔티티에 generatedValue 추가

back/backend/src/main/java/org/example/backend/Config/SecurityConfig.java, back/backend/src/main/java/org/example/backend/Security/CustomUserDetailService.java, back/backend/src/main/java/org/example/backend/Security/CustomUserDetails.java, back/backend/src/main/java/org/example/backend/User/Controller/UserController.java
close #592 
- 없는 계정으로 로그인시 생기는 오류 수정
- 로그아웃시 JSESSIONID 쿠키도 같이 삭제
=> [Fix] 로그인 핫픽스
