beyond-sw-camp/be06-fin-SENAGAE-Enadu

- backend/src/main/java/org/example/backend/Exception/GlobalExceptionHandler.java
- backend/src/main/java/org/example/backend/Exception/custom/InvalidCustomException.java
close #123 
- GlobalExceptionHandler 생성
```
@RestControllerAdvice
@Order(value = 1)
public class GlobalExceptionHandler {
@ExceptionHandler(RuntimeException.class)
public BaseResponse<String> handleGlobalException(InvalidCustomException e) {
return new BaseResponse<>(e.getStatus());
}
}
```
- InvalidCustomException 생성
```
@Getter
public class InvalidCustomException extends RuntimeException {
private final BaseResponseStatus status;
public InvalidCustomException(BaseResponseStatus status) {
this.status = status;
}
}
```
- InvalidCutomExceptio을 상속 받는 예외가 RestController에서throw 되면,  GlobalExceptionHandler가 잡아서 해당 예외의 BaseResponseStatus를 읽어서 응답을 보낸다.
> [Feat] GlobalExceptionHandler, InvalidCustomException 생성 (#123)

- backend/src/main/java/org/example/backend/Chat/Controller/ChatController.java
- backend/src/main/java/org/example/backend/Chat/Model/ChatRoomRes.java
- backend/src/main/java/org/example/backend/Chat/Repository/ChatRoomRepository.java
- backend/src/main/java/org/example/backend/Chat/Service/ChatService.java
close #55
- 채팅방 목록 조회 API 구현
- 로그인한 사용자의 정보는 임의로 id=1인 유저로 구현
- ChatRoom 엔티티의 user1_id 와 user2_id 중 하나라도 값이 id 인 ChatRoom 엔티티를 모두 조회 후 상대방의 닉네임과 프로필 이미지를 가져오고, 해당 ChatRoom을 외래키로 가지는 chat 엔티티중 가장 최신 데이터의 메세지와 send_time을 가져온다.
- 위에서 가져온 데이터로 response 객체를 만들고 리스트에 담는다.
- 리스트의 lastMessageDay 값으로 정렬하여 응답으로 보낸다.
```
{
"code": 1000,
"result": [
{
"chatRoomId": 2,
"recipientName": "김우혁",
"recipientProfile": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/08/95b69c0a-b44c-43f4-bebf-4d86e77d735c",
"lastMessage": "메세지4",
"lastMessageDay": "2024-09-08T16:02:10"
},
{
"chatRoomId": 1,
"recipientName": "혁우김",
"recipientProfile": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/08/95b69c0a-b44c-43f4-bebf-4d86e77d735c",
"lastMessage": …
```
> [Feat] 채팅방 리스트 조회 API 구현 (#55)

- backend/src/main/java/org/example/backend/Category/Model/Entity/Category.java
- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Exception/custom/InvalidCategoryException.java
- backend/src/main/java/org/example/backend/Exception/custom/InvalidWikiException.java
- backend/src/main/java/org/example/backend/File/Service/CloudFileUploadService.java
- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Entity/Wiki.java
- backend/src/main/java/org/example/backend/Wiki/Model/Entity/WikiContent.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiRegisterReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/WikiRegisterRes.java
- backend/src/main/java/org/example/backend/Wiki/Repository/LatestWikiRepository.java
- backend/src/main/java/org/example/backend/Wiki/Repository/WikiContentRepository.java
- backend/src/main/java/org/example/backend/Wiki/Repository/WikiRepository.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
- backend/src/main/resources/application.yml
close #23
- 위키 등록시 사용자 Req에 의해 썸네일, 위키 내용 저장
- 위키 등록할 때(수정 x, 젤 처음 등록) 제목, 내용, 카테고리가 필요한데 위키 Entity에는 title이 없었음. => Wiki Entity에 title 추가
- Wiki와 Category 연관관계 수정. => OneToOne에서 ManyToOne
- content 안의 사진 업로드시, 사진 경로 URL은 컬럼의 content에 같이 저장 처리
- Response는 위키의 ID 반환
- 유저 권한 설정은 추후에 추가 예정
- 위키 등록 예외처리 추후에 추가 예정
- 위키 등록 시  해당 위키 제목, 버전(1)이 있으면 등록 불가 처리 예정
> [Feat] 위키 등록 백엔드 API (#23)

- backend/src/main/java/org/example/backend/Category/Repository/CategoryRepository.java
- backend/src/main/java/org/example/backend/Config/SecurityConfig.java
- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
close #34 
- 질문 등록 시 CustomUserDetails를 받을 수 있도록 설정
- CustomUserDetails의 email 데이터를 이용하여 해당 이메일을 username으로 가지는 USER를 조회
- 해당 USER를 QnA DB에 저장
> [Fix] Qna 질문 등록 기능 CustomUserDetails를 활용한 유저 데이터 연결

- frontend/src/components/Category/CategoryItemComponent.vue
- frontend/src/components/Category/SubCategoryModal.vue
- frontend/src/components/Category/SuperCategoryModal.vue
- frontend/src/store/useCategoryStore.js
close #74, #77, #68
백엔드 카테고리 검색 로직 불필요 #49
- 상위 카테고리 선택, 하위 카테고리 선택 모달 UI 구현
- 선택한 카테고리 상위 컴포넌트로 전달 기능 추가 (객체로 id, categoryName 포함)
- useUserStore에 getters를 추가해서 백엔드에 검색 로직 필요 없이 불러온 값에서 검색 기능 구현
선택하면 : @mySuperCategory(객체 변수명도 mySuperCategory )
그냥 닫기 : @closeSuper
선택하면 : @mySubCategory(객체 변수명도 mySubCategory )
그냥 닫기 : @closeSub
superCategory 객체(id, categoryName) props로 전달 필요
머지 한 다음에 서브쪽 잘 작동하는지 확인 필요(props 값을 받았다 생각하고 구현)
> [Feat] 카테고리 모달 추가 (#74, #77, #68)

- frontend/src/components/Chat/ChatComponent.vue
- frontend/src/components/Chat/ChatMessageComponent.vue
- frontend/src/components/Chat/ChatNavComponent.vue
- frontend/src/components/Chat/ChatRoomComponent.vue
- frontend/src/pages/ChatPgae.vue
- frontend/src/router/index.js
- frontend/src/store/useChatStore.js
close #96, #82 
- 채팅방 컴포넌트 생성
- ul 태그의 column 순서를 reverse로 설정하여 무한 스크롤로 새로운 페이지 불러오면 맨 위에 메세지가 생성됨
- 채팅 메세지 컴포넌트 생성
- 응답으로 들어온 userId와 recipientId가 같으면 상대방이므로 프로필 이미지, 상대방 닉네임, 메세지, 보낸 시간이 뜬다.
- 만약 이전 메세지의 보낸 날짜와 현재 메세지의 보낸 날짜가 다르면 날짜를 표시해준다.
- 만약 맨 마지막 메세지일 경우에도 날짜를 표시해준다.
- 백엔드 API 연결
- 요청으로 chatRoomId, page, size를 보낸다. 
- 채팅 페이지로 종합
> [Feat] 채팅 내역 조회 컴포넌트, 채팅 페이지 생성 (#96, #82)

- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/Res/GetQnaListRes.java
close #36 
- customUserDetails를 활용 user데이터를 넣어, 목록 조회 구현
- 카테고리 쪽에 sub나 super에 null 값을 넣는 것, 즉 둘 중 하나의 데이터만 넣을 수 있는 것에 대한 처리가 필요함
- 일시적으로
이런식으로 처리함 => 후에 카테고리 단계에서 처리 되면 지울 예정
- 또한 db상에서 관계 키 문제라고는 뜨는데 정확한 이유는 모르겠으나 동일한 카테고리id를 사용하여, 서로 다른 qna에 등록할 수 없는 문제가 확인됨 (논의 필요)
> [Fix] qna 목록 조회 customUserDetails를 활용한 유저 정보 데이터 조회 기능 추가

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #23
- 위키 등록시 CustomUserDetails를 활용하여 유저ID 조회 후 등록 가능하게 수정
- 위키 등록시 작성자 ID wiki content에 저장
> [Fix] 위키 등록 기능 CustomUserDetails를 활용한 유저 데이터 연결 (#23)

- backend/build.gradle
- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Config/SecurityConfig.java
- backend/src/main/java/org/example/backend/Exception/CustomAuthenticationFailureHandler.java
- backend/src/main/java/org/example/backend/Security/CustomOAuth2User.java
- backend/src/main/java/org/example/backend/Security/CustomOAuth2UserService.java
- backend/src/main/java/org/example/backend/Security/OAuth2LoginSuccessHandler.java
- backend/src/main/java/org/example/backend/User/Model/Entity/User.java
- backend/src/main/java/org/example/backend/User/Repository/UserRepository.java
- backend/src/main/resources/application.yml
close #2 
close #5 
- /oauth2/authorization/github에서 깃허브 계정으로 로그인 후 로직 처리
- 이메일 가져와서 db에서 검사 후 없으면 회원가입 후 로그인 처리, 있으면 바로 로그인 처리
- 일반 로그인과 동일하게 JWT 토큰 쿠키에 추가
본인 깃허브 계정으로 잘 되는지 :8080/oauth2/authorization/github 로 접속해서 확인해주세용
> [Feat] 깃허브 로그인, 회원가입 추가 (#2, #5)

- backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/Res/GetQuestionDetailRes.java
close  #103 , #100, #101 
- customUserDetails를 컨트롤러에서 id 데이터로 처리하여 서비스로 전달하도록 로직 수정
- 상위 카테고리 데이터 조회 시 null에 대한 예외 처리
- qnaDetail 데이터 받는 형식 수정
> [Fix] Qna 전체 서비스 로직 수정

- backend/src/main/java/org/example/backend/BackendApplication.java
- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Entity/LatestWiki.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiListReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiListReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiRegisterReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/WikiListRes.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #26 
📌 위키 목록 전체 조회 기능
- 생성일 기준으로 최신순 정렬 처리
- 제목, 내용, 썸네일, 카테고리 출력
- 페이징 처리 (eq에 page, size 입력 안해도 size 20으로 고정 처리)
예외처리는 필요없는 것 같아서 안했는데, 확인해보고 리뷰 부탁드려용
> [Feat] 위키 목록 조회 API 구현 (#26)

- backend/src/main/java/org/example/backend/BackendApplication.java
- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Entity/WikiContent.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiDetailReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiDetailRes.java
- backend/src/main/java/org/example/backend/Wiki/Repository/WikiContentRepository.java
- backend/src/main/java/org/example/backend/Wiki/Repository/WikiScrapRepository.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #27
📌위키 상세 조회
- 위키(최신버전) 상세조회 기능 구현
- 로그인 한 유저일 시, 스크랩 여부 확인하고 T/F 반환
- 미로그인 유저일 시, 스크랩 여부 fale로 반환
- 제목, 내용, 카테고리, 버전, 스크랩 여부 반환
> [Feat] 위키 상세조회 API (#27)

- backend/src/main/java/org/example/backend/Config/SecurityConfig.java
- backend/src/main/java/org/example/backend/Point/Controller/PointController.java
- backend/src/main/java/org/example/backend/Point/Model/Entity/PointDetail.java
- backend/src/main/java/org/example/backend/Point/Model/Res/GetPointHistoryRes.java
- backend/src/main/java/org/example/backend/Point/Repository/PointRepository.java
- backend/src/main/java/org/example/backend/Point/Service/PointService.java
close #64 
**로그인한 사용자의 포인트 내역 조회**
- 로그인한 사용자의 id로 PointDetail 테이블을 조회
- 페이징 처리하여 반환
- point, state(적립true/차감false), description, createdAt
```
{
"code": 1000,
"result": [
{
"point": 10,
"state": true,
"description": "질문글 작성",
"createdAt": "2024-09-13T15:35:41"
},
{
"point": 10,
"state": true,
"description": "질문글 작성",
"createdAt": "2024-09-13T15:35:41"
},
{
"point": 10,
"state": true,
"description": "질문글 작성",
"createdAt": "2024-09-11T15:35:41"
}
]
}
```
로그인한 사용자가 아닐 경우에 대한 처리는 spring security에서 설정함
> [Feat] 포인트 내역 조회 API 구현 (#64)

- backend/src/main/java/org/example/backend/Config/SecurityConfig.java
- backend/src/main/java/org/example/backend/Exception/CustomAuthenticationEntryPoint.java
close #185 
스프링 시큐리티 설정으로 인가받지 않은 사용자가 인가가 필요한 API 호출시 예외 처리 설정
``` java
@Component
public class CustomAuthenticationEntryPoint implements AuthenticationEntryPoint {
private final Gson gson = new Gson();
@Override
public void commence(HttpServletRequest request, HttpServletResponse response, AuthenticationException authException) throws IOException {
response.setCharacterEncoding("UTF-8");
response.setContentType("application/json; charset=UTF-8");
PrintWriter out = response.getWriter();
String jsonResponse = gson.toJson(new BaseResponse<>(BaseResponseStatus.USER_NOT_LOGIN));
out.print(jsonResponse);
}
}
```
> [Feat] Spring Security 설정으로 로그인 ì설정으로 인가받지 못한 사용자 처리 (#185)

- frontend/public/index.html
- frontend/src/App.vue
- frontend/src/components/Common/PaginationComponent.vue
- frontend/src/components/Common/SortTypeComponent.vue
- frontend/src/components/qna/QnaAnswerDetailComponent.vue
- frontend/src/components/qna/QnaCommentDetailComponent.vue
- frontend/src/components/qna/QnaDetailComponent.vue
- frontend/src/components/qna/QnaDetailHeader.vue
- frontend/src/components/qna/QnaDetailHeaderComponent.vue
- frontend/src/components/qna/QnaListCardComponent.vue
- frontend/src/pages/QnaDetailPage.vue
- frontend/src/pages/QnaListPage.vue
- frontend/src/router/index.js
- frontend/src/store/useQnaStore.js
- frontend/src/utils/FormatDate.js
close #37 
- v-for를 이용해 질문에서 답변 리스트를, 답변에서 댓글 리스트를 가져올 수 있도록 로직 구현
- props를 이용하여 상위 컴포넌트에서 데이터를 받아, vue 파일로 출력 될 수 있도록 처리
- 백엔드의 상세조회 부분과 store를 이용하여 연동
참고 사항
- 현재 좋아요 표시 형태에 문제가 있으나, 후에 질문 및 답변 좋아요/싫어요 로직을 구현하는 과정에서 binding을 통해 해결 할 수 있을 것으로 예상,
- editer의 viewer를 사용해서 기존에 p태그 안에 넣어 놓은 각 내용(작성된 글)을 출력하는 로직 필요
> [Fix] qna 상세 조회 (질문/답변/댓글) 전체 조회 구현 

- frontend/src/components/Common/PaginationComponent.vue
- frontend/src/components/Point/PointHistoryComponent.vue
- frontend/src/components/Point/PointInfoComponent.vue
- frontend/src/components/qna/QnaListCardComponent.vue
- frontend/src/pages/PointPage.vue
- frontend/src/router/index.js
- frontend/src/store/usePointStore.js
close #62 
✅ 포인트 내역 컴포넌트 구현
- 포인트
- 적립/차감 여부
- 날짜
- 이유
✅ 자신의 총 포인트와 랭킹을 표시
✅ 포인트 조회 페이지 구현
- 페이징 처리
PaginationComponent 수정함
페이지는 최대 5개 까지 표시되고, totalPage를 상위 컴포넌트 혹은 페이지에서 받아서 5개보다 페이지가 많으면 <<,   >> 으로 처리
> [Feat] 포인트 내역 페이지 구현 (#62)

- frontend/src/components/Header/HeaderComponent.vue
- frontend/src/components/qna/QnaListCardComponent.vue
- frontend/src/components/user/SignInComponent.vue
- frontend/src/pages/QnaListPage.vue
- 헤더에 임시로 라우터 추가
- 마이페이지 버튼 드롭다운으로 변경 (회원 정보, 작성 목록, 스크랩 목록, 포인트 및 랭킹, 채팅) 
- 깃허브 로그인 버튼 이미지 수정
- 로그아웃 후 alert 추가
- QnA 목록 css 수정
> [Fix] 마이페이지 버튼 드롭다운으로 수정

- backend/src/main/java/org/example/backend/Chat/Model/Entity/Chat.java
- backend/src/main/java/org/example/backend/Point/Aop/PointAop.java
- backend/src/main/java/org/example/backend/Point/Model/Entity/PointDetail.java
- backend/src/main/java/org/example/backend/Point/Model/Enum/PointDescriptionEnum.java
- backend/src/main/java/org/example/backend/Point/Service/PointService.java
- backend/src/main/java/org/example/backend/User/Model/Entity/User.java
close #60 
포인트 적립/차감 메서드 구현
AOP를 활용하여 적립/차감이 일어날 Method가 정상 종료되면 포인트 적립/차감 메서드가 실행되도록 구현
적립/차감 설명은 Enum으로 관리
적립/차감 후 point에 따라 user의 등급도 업데이트
현재는 위키 등록, 질문글 등록, 에러아카이브 등록할 때만 포인트 적립됨
나머지 메서드들도 추가되면 이후 수정 예정
> [Feat] 포인트 적립/차감 AOP 구현 (#60)

- backend/src/main/java/org/example/backend/Chat/Controller/ChatController.java
- backend/src/main/java/org/example/backend/Chat/Model/Req/StartChatReq.java
- backend/src/main/java/org/example/backend/Chat/Model/Res/StartChatRes.java
- backend/src/main/java/org/example/backend/Chat/Repository/ChatRoomRepository.java
- backend/src/main/java/org/example/backend/Chat/Service/ChatService.java
close #52 
- 채팅 시작 API 구현
- 상대방의 닉네임을 통해 상대방의 User 엔티티 조회
- 나의 user id 와 상대방의 user id 중 작은쪽이 user1, 큰쪽이 user2
- ChatRoom을 user1, user2로 및 저장
- 이미 상대방과의 채팅방이 있을 경우 해당 채팅방을 조회
- 응답으로 채팅방 id, 상대방 id, 상대방 닉네임, 프로필 이미지를 반환
``` json
{
"code": 1000,
"result": {
"chatRoomId": 4,
"recipientNickname": "test01",
"recipientProfile": "https://enadu.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/15/3ebf7f81-7f52-4309-8eb5-d79f5a5e8007",
"recipientId": 3
}
}
```
> [Feat] 채팅 시작 API 구현 (#52)

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/File/Service/CloudFileUploadService.java
- backend/src/main/java/org/example/backend/User/Controller/UserController.java
- backend/src/main/java/org/example/backend/User/Model/Entity/User.java
- backend/src/main/java/org/example/backend/User/Model/Req/UpdateUserPasswordReq.java
- backend/src/main/java/org/example/backend/User/Model/Res/GetUserInfoRes.java
- backend/src/main/java/org/example/backend/User/Service/UserService.java
close #16, #17, #18, #20
- 유저 엔티티 수정
- 비밀번호 확인, 비밀번호 수정, 회원탈퇴, 회원정보 조회 추가
- 유저 업데이트 관련 api String 타입 말고 Map<String, String> 으로 바꾸고 .get()으로 데이터 사용으로 수정
- 파일 업데이트 서비스 .JPG로  되어있으면 파일타입 오류 뜨는거 수정
> [Feat] 비밀번호 확인, 비밀번호 수정, 회원탈퇴, 회원 정보 조회 추가 (#16, #17, #18, #20)

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Security/CustomUserDetails.java
- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Entity/LatestWiki.java
- backend/src/main/java/org/example/backend/Wiki/Model/Entity/WikiContent.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiUpdateReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiDetailRes.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiUpdateRes.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #25 
📌위키 수정(버전 업데이트) 기능
- 위키 수정시, 버전 +1로 처리되어 버전 갱신
- 썸네일, 내용만 수정 가능
- 썸네일 미등록시 이전 버전 위키의 썸네일 들고오도록 처리
- 회원등급에 따른 수정 제한 처리
- 수정한 유저 정보도 함께 저장
💡비로그인 유저에게는 GUEST 등급 부여함 => null로 관리하기엔  비로그인 상태인지, 등급을 제대로 가져오지 못한 것인지 명확하지 않을 수 있을 것 같고, 유연한 관리 차원
> [Feat] 위키 수정(버전 업데이트) API (#25)

- .idea/.gitignore
- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorArchive.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorLike.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Entity/ErrorScrap.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Req/GetErrorArchiveDetailReq.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Res/GetErrorArchiveDetailRes.java
- backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorLikeRepository.java
- backend/src/main/java/org/example/backend/ErrorArchive/Repository/ErrorScrapRepository.java
- backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
- backend/src/main/resources/application.yml
close #10 
로그인한 사용자가 자신이 좋아요/싫어요 한 에러 아카이브 상세를 조회 할 수 있음
서비스단에 ErrorArchiveLikeOrHate 메소드 추가해서, 
에러아카이브와 사용자Id로 사용자를 조회해서 사용자와 에러아카이브로 좋아요/싫어요를 조회
로그인한 사용자가 자신이 스크랩한 에러 아카이브 상세를 조회할 수 있음
서비스단에 ErrorArchiveScrap 메소드 추가해서,
에러아카이브와 사용자Id로 사용자를 조회해서 사용자와 에러아카이브로 스크랩 여부를 조회
> [Feat] 에러 아카이브 상세 조회 api 구현(#10)

- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiVersionListReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiVersionListRes.java
- backend/src/main/java/org/example/backend/Wiki/Repository/WikiContentRepository.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #33 
📌사용자가 선택한 위키의 이전 버전 목록 조회
- 페이징 처리 및 정렬 설정(createdAt 기준 내림차순)
> [Feat] 위키 이전버전 목록 조회 API (#33)

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Req/ListErrorArchiveReq.java
- backend/src/main/java/org/example/backend/ErrorArchive/Model/Res/ListErrorArchiveRes.java
- backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
close #이슈번호
- 좋아요순, 최신순으로 목록 조회 추가 (기본값은 최신순)
- 에러아카이브 엔티티의 데이터를 페이지 단위로 가져오는 메소드 추가
> [Feat] 에러 아카이브 목록 조회 수정(최신순, 좋아요순)

- frontend/src/components/Common/SortTypeComponent.vue
- frontend/src/components/errorarchive/ErrorArchiveCardComponent.vue
- frontend/src/components/errorarchive/ErrorArchiveRegisterComponent.vue
- frontend/src/components/user/SignUpComponent.vue
- frontend/src/pages/ErrorArchiveListPage.vue
- frontend/src/router/index.js
- frontend/src/store/useErrorArchiveStore.js
close #221 
에러아카이브 목록을 최신순, 좋아요순으로 볼 수 있게 처리
데이터베이스에 데이터양에 맞게 페이지 설정(this.totalPage = this.errorarchiveStore.errorarchiveCards[0].totalPage)
> [Feat] 에러 아카이브 목록 조회(최신순, 좋아요순)

- frontend/src/store/useChatStore.js
- 채팅페이지에 접속했을 때 연결 맺고 있지 않으면, 페이지를 벗어나지 못하는 현상 수정
- 페이지를 벗어날 때 disconnect하는데 맺고있는 연결이 있을 때만 disconnect하도로고 수정
> [Fix] 채팅 페이지에서 라우팅 안되는 현상 수정

- frontend/src/store/useErrorArchiveStore.js
merge하면서 errorarchivestore의 state에 comma가 빠져서 생긴 오류 해결
> [Fix] useErrorArchiveStore state에 comma 추가

- frontend/src/components/wiki/WikiDetailComponent.vue
- frontend/src/components/wiki/WikiRegisterComponent.vue
- frontend/src/components/wiki/WikiUpdateComponent.vue
- frontend/src/main.js
- frontend/src/pages/WikiDetailPage.vue
- frontend/src/pages/WikiUpdatePage.vue
- frontend/src/router/index.js
- frontend/src/store/useWikiStore.js
close #79 
📌위키 수정 기능 구현
- 위키 thumbnail, content만 수정 가능하도록 설정
- 썸네일 미등록시, 기존 썸네일을 유지하도록 로직 구성
- 페이지 라우터 설정
- axios 설정
- 권한이 있는 사용자만 수정 버튼을 볼 수 있도록 구현
- 비로그인 유저, '뉴비' 등급은 수정 권한이 없으며, 해당 등급에 해당하는 사용자는 수정 버튼을 보지 못하게 설정
- 수정 완료시, 버전 업데이트 되어 현재 버전과 함께 상세페이지로 리다이렉트 처리
아직 이쁘게 꾸미지는 못했엉 ^_ㅠ
> [Feat] 위키 수정(버전 업데이트) 기능 (#79)

- frontend/src/components/errorarchive/ErrorArchiveRegisterComponent.vue
- frontend/src/components/qna/QnaRegisterComponent.vue
- frontend/src/components/wiki/WikiRegisterComponent.vue
- frontend/src/store/useCommonStore.js
close #225 
- 게시글 등록 시 이미지 업로드 기능 추가
- 아래와 같이 사용하면 된다.
- 위키 등록, 에러아카이브 등록, QnA등록엔 적용 해놓았다.
``` html
<v-md-editor v-model="myText" :disabled-menus="[]" @upload-image="commonStore.imageUpload" height="400px"></v-md-editor>
```
useCommonStore.js
``` javascript
async imageUpload(event, insertImage, files){
try {
const formData = new FormData();
formData.append('imgFile', files[0]);
const response= await axios.post(backend+'/img/upload', formData, {
headers: { 'Content-Type': 'multipart/form-data' },
withCredentials: true
});
insertImage({
url:response.data.result,
desc: 'desc',
width: 'auto',
height: 'auto'
});
} catch (error) {
console.error('이미지 업로드 실패:', error);
return null;  // 업로드 실패 시 null 반환
}
}
```
> [Feat] 게시글 등록할 시 이미지 업로드기능 추가 (#225)

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Repository/AnswerLikeRepository.java
- backend/src/main/java/org/example/backend/Qna/Repository/QnaLikeRepository.java
- backend/src/main/java/org/example/backend/Qna/Repository/QnaScrapRepository.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/Answer.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/AnswerComment.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/AnswerLike.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/QnaBoard.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerDetailListRes.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionDetailRes.java
- backend/src/main/java/org/example/backend/User/Model/Entity/User.java
close #39 #40 
- 좋아요 및 싫어요 각각의 선택 api 구현
- 기존 상태가 선택 상태일 때 해당 like또는 hate를 제거하고 cnt 업데이트
- scrap 선택 api 구현
- 기존 스크랩한 질문의 경우 스크랩 취소
- 질문의 상세 조회에서 현재 사용자가 스크랩 또는 좋아요 및 싫어요를 표기했는지여부를 boolean 값으로 전달
- 각종 에러처리
> [Feat] Qna 좋아요, 싫어요 및 스크랩 설정 및 검증 메소드 구현

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Repository/AnswerLikeRepository.java
- backend/src/main/java/org/example/backend/Qna/Repository/QnaLikeRepository.java
- backend/src/main/java/org/example/backend/Qna/Repository/QnaScrapRepository.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/Answer.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/AnswerComment.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/AnswerLike.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/QnaBoard.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerDetailListRes.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionDetailRes.java
- backend/src/main/java/org/example/backend/User/Model/Entity/User.java
close #48 
- 좋아요 및 싫어요 각각의 선택 api 구현
- 기존 상태가 선택 상태일 때 해당 like또는 hate를 제거하고 cnt 업데이트
- 답변의 상세 조회에서 현재 사용자가 좋아요 및 싫어요를 표기했는지여부를 boolean 값으로 전달
- 각종 에러 처리
> [Feat] 답변에 관한 좋아요 및 싫어요 api 구현

- frontend/src/components/Common/SearchComponent.vue
- frontend/src/components/Common/SortTypeComponent.vue
- frontend/src/pages/QnaListPage.vue
- 목록 페이지에서 사용할 검색 컴포넌트 생성
- 먼저 상위 카테고리를 선택 후 '모든 하위 카테고리 선택'버튼을 눌러 모든 하위 카테고리를 볼 수 있는 모달을 띄움
- 하위  카테고리를 선택하면 선택한 카테고리가 표시됨
- 선택 취소 버튼을 누르면 선택한 하위 카테고리가 취소됨
- SortTypeComponent를 검색 컴포넌트로 이동
- SortTypeComponent가 페이지 진입시 바로 최신순이 선택되어 있도록 수정
> [Feat] 검색 컴포넌트 생성 및 qna 목록 조회에 적용

- frontend/src/components/Header/HeaderComponent.vue
- frontend/src/components/wiki/WikiCardComponent.vue
- frontend/src/pages/WikiListPage.vue
- frontend/src/router/index.js
- frontend/src/store/useWikiStore.js
close #84 
- 위키 카드 컴포넌트 구현
- 위키 목록 페이지
- 목록에서 카드 클릭 시, 상세페이지로 라우팅 처리
- 헤더 위키 클릭 시 위키 목록 페이지로 라우팅 처리
- 하단 버튼에 전체 페이지 수 출력 처리
> [Feat] 위키 목록 조회 (#84)

- frontend/src/components/wiki/WikiDetailComponent.vue
- frontend/src/components/wiki/WikiVersionDetailComponent.vue
- frontend/src/pages/WikiVersionDetailPage.vue
- frontend/src/pages/WikiVersionListPage.vue
- frontend/src/router/index.js
- frontend/src/store/useWikiStore.js
close #245 #246 
📌**이전버전 목록조회 기능, 이전버전 상세조회 기능**
- 위키의 이전 버전 목록을 조회하고 사용자가 특정 버전을 클릭 시, 해당 버전의 상세 페이지로 이동하는 기능 구현
- 특정 위키 버전의 상세 정보를 조회 시, 최신 버전으로 갈 수 있는 기능 구현
- 페이지네이션 기능 추가
- 각 버전 링크 클릭 시 해당 버전의 상세 페이지 routing 설정
- [최신 위키 돌아가기] 버튼을 추가하여 사용자가 최신 버전으로 돌아갈 수 있도록 routing 설정
- UI 수정
- 그 외 위키 여러 컴포넌트 수정
최신 버전 위키 상세 페이지 UI
이전 버전 위키 클릭 시 UI
이전 버전(ex. V12) 클릭 시 UI
버전 롤백 API 미구현으로 아직 목록에 안 넣었습니다. 추후 추가 예정
> [Feat] 위키 이전버전 목록조회 기능, 이전버전 상세조회 기능  (#245 #246)

- frontend/src/components/Common/LoadingComponent.vue
- frontend/src/components/Common/TagComponent.vue
- frontend/src/components/Header/HeaderComponent.vue
- frontend/src/components/errorarchive/ErrorArchiveCardComponent.vue
- frontend/src/components/qna/QnaDetailHeaderComponent.vue
- frontend/src/components/qna/QnaListCardComponent.vue
- frontend/src/pages/ErrorArchiveListPage.vue
- frontend/src/pages/MainPage.vue
- frontend/src/pages/QnaListPage.vue
- frontend/src/pages/WikiListPage.vue
- frontend/src/router/index.js
- frontend/src/store/useMainStore.js
close #61 
- 메인 페이지 구성
- TagComponent 생성 및 각 목록 페이지에 적용
- props로 tagTitle이랑 tagSubTitle 주면 됨(메인 페이지 참고)
- LoadingComponent 생성 및 메인 페이지에 적용
- 그냥 사용하면됨(메인페이지 참고)
- 위키 목록 가운데 정렬 안되어 있어 css 수정
- 에러아카이브 카드 클릭시 상세 페이지로 routing 설정
- QnA 카드 마우스 올리면 pointer 바꾸는 css추가
- 헤더에 아카이브 routing 설정
> [Feat] 메인 페이지 구현 및 API 연결(#61)

- frontend/src/components/user/SignUpComponent.vue
- frontend/src/pages/EmailVerifyPage.vue
- frontend/src/router/index.js
- frontend/src/store/useUserStore.js
close #
닉네임 중복 수정 
이메일 인증 페이지 생성, axios 연결
1. 이메일 인증 페이지 만들고 routing 설정
2. 해당 페이지에서 api 호출
3. 이메일에서 링크를 클릭하면 우리 페이지가 뜨고 뜨는 순간 api 호출되어서 email, uuid 날라가고
4. 백엔드에서 확인한 후 결과값을 응답으로 보냄
5. 프론트에서 응답이 성공
6. 로그인 버튼을 누르면 /login 경로로 이동
> [Feat] 이메일 인증 페이지 생성, axios 연결, 닉네임 중복 확인 수정

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Common/GlobalMessage.java
- backend/src/main/java/org/example/backend/EmailVerify/Controller/EmailVerifyController.java
- backend/src/main/java/org/example/backend/EmailVerify/Model/Entity/EmailVerify.java
- backend/src/main/java/org/example/backend/EmailVerify/Repository/EmailVerifyRepository.java
- backend/src/main/java/org/example/backend/EmailVerify/Service/EmailVerifyService.java
- backend/src/main/java/org/example/backend/Exception/custom/InvalidEmailException.java
- backend/src/main/java/org/example/backend/User/Controller/UserController.java
- backend/src/main/java/org/example/backend/User/Model/Entity/User.java
- backend/src/main/java/org/example/backend/User/Service/UserService.java
- backend/src/main/resources/application.yml
close #3 
이메일 인증 로직은 다음과 같음
1. 회원은 인증 받을 이메일을 요청에 포함하여 서버에 보냄
2. 서버는 일정 시간 동안 인증 코드를 발행함
3. 서버는 인증 코드를 회원에게 받은 이메일로 전송함
4. 회원은 입력 받은 인증 코드를 요청에 포함하여 서버에 보냄
5. 회원의 verify의 상태는 true가 됨
> [Feat] 회원가입 시 이메일 인증 api 구현(#3)

- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiRollbackReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/WikiRollbackRes.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #31 
📌 위키 롤백 기능
위키 이전버전 목록조회에서 원하는 버전을 선택하여 최신 버전으로 롤백 시킬 수 있다.
- 비로그인 유저, 뉴비 등급은 롤백 권한 제한
- 해당 버전의 위키는 최신 버전으로 갱신
> [Feat] 위키 롤백 API (#31)

- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiScrapReq.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/GetWikiDetailRes.java
- backend/src/main/java/org/example/backend/Wiki/Model/Res/WikiScrapRes.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
close #32 
📌위키 스크랩 API 구현
- contentId로 스크랩 실행
- 재스크랩 시, 취소 처리 (DB에서 삭제)
- 첫 스크랩 시, Scrap DB에 contentId, userId 값 삽입 
> [Feat] 위키 스크랩 API (#32)

- backend/src/main/java/org/example/backend/EmailVerify/Service/EmailVerifyService.java
- FRONT_URL 에 static이 설정되어있었는데 @Value 어노테이션을 쓸라면 static이 붙으면 안돼서 제거해줬다.
> [Fix] FRONT_URL 상수에 static 삭제

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiSearchReq.java
- backend/src/main/java/org/example/backend/Wiki/Repository/WikiRepository.java
- backend/src/main/java/org/example/backend/Wiki/Service/DbWikiSearchService.java
- backend/src/main/java/org/example/backend/Wiki/Service/WikiSearchService.java
close #29 
📌 위키 검색 API 구현
유저는 제목/내용/ 제목+내용/ 검색 타입을 선택할 수 있다.
유저는 검색어/ 카테고리/ 검색어+카테고리 조건으로 선택하여 검색할 수있다.
- 검색어 공백 삭제, 소문자 변환 처리
- 유효성 확인 메서드 추가하여 type이 유효하지않거나, 검색 조건이 모두 null이면 예외처리
- 카테고리id는 wiki 테이블, 컨텐츠는 latestWiki 테이블에서 가져옴
> [Feat] 위키 검색 API (#29)

- frontend/src/components/errorarchive/ErrorArchiveCardComponent.vue
close #이슈번호
제목이 길어져도 카드의 크기는 고정되게 수정
제목의 길이가 넘치면 숨김
> [Fix] 제목이 길어져도 카드의 크기는 고정되게 수정

- frontend/Dockerfile
close #이슈번호
- dockerfile에 icon이 dist/icon 파일이 없어 오류나던 현상 해결
- icon부분 주석처리
> [Fix] Dockerfile에 icon 주석처리

- frontend/src/components/wiki/WikiCardComponent.vue
- frontend/src/pages/WikiVersionListPage.vue
close #380 #362
📌위키 카드 사이즈 css 수정
- 본문 내용에 따라 사이즈가 유동적이었는데, 고정 사이즈로 수정
📌위키 버전 목록 등급 안내 css 수정
- 페이지네이션 css 수정에 따른 안내 멘트 깨짐 오류 해결
> [Fix] 위키 카드 사이즈 수정, 위키 버전 목록 등급 안내 css 수정 (#380,#362)

- backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- backend/src/main/java/org/example/backend/Qna/Controller/AnswerController.java
- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerStateRes.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetQuestionStateRes.java
close #215 
비 로그인 사용 자의 접근 권한 부여 (채택, 등록, 좋아요 scrap 제외 단순 조회 기능)
질문 및 답변의 좋아요 및 싫어요와 그 수 및 질문의 스크랩 여부를 조회하는 api 구현
> [Fix] qna에 비로그인 사용자의 접근 권한 범위 지정 및 좋아요 및 스크랩 조회 메커니즘 구현

- backend/src/main/java/org/example/backend/Qna/Repository/QuestionRepository.java
- backend/src/main/java/org/example/backend/Qna/Service/BasicQnaSearchService.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/QnaBoard.java
close #301 
검색 시 카테고리 미 선택 시, 카테고리 구분없이 검색되도록 쿼리 수정
> [Fix] Qna 검색 시 카테고리 미 선택 데이터에 대한 처리 방식 변경

- frontend/src/components/wiki/WikiUpdateComponent.vue
close #402 
📌 위키 수정 컴포넌트 수정
- 제목, 카테고리란에 pointer-events: none; 추가해서 더블 클릭 시, 인풋창 안보이게 처리
변경 전
변경 후
> [Fix] 위키 수정 컴포넌트 수정 (#402)

- frontend/package-lock.json
- frontend/src/components/Common/AdditionalInfoComponent.vue
- frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue
- frontend/src/components/Qna/Detail/QnaDetailHeaderComponent.vue
- frontend/src/store/useQnaStore.js
close #289 
채택 마크 생성 메커니즘 수정
버튼 태그의 채택 또는 수정을 통해 답변 데이터를 변경 했을 때, 버튼이 종료되도록 설정
이미 채택된 답변에서 더 이상 선택할 수 있는 항목이 없을 때 뜨는 css 제거 
.=> 이거 수정
> [Fix] 답변 채택 이후 데이터 전환 메커니즘과 버튼의 상태 수정

- backend/src/main/java/org/example/backend/Qna/Controller/AnswerController.java
- backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/AnswerLike.java
- backend/src/main/java/org/example/backend/Qna/model/Entity/QnaLike.java
- backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerStateRes.java
close #410 
좋아요 및 싫어요 상태가 충돌 날 경우 이후 상태로 강제 변경되도록 메커니즘 수정
좋아요 및 싫어요, 스크랩 컨트롤러 요청의 반환 테이터를 id에서 state 데이터로 수정
기존 state를 가져오는 컨트롤러와 서비스 메소드는 예비용으로 남겨둠
> [Fix] 좋아요 버튼 충돌 시의 메커니즘 수정

- back/backend/build.gradle
- back/backend/docker-compose.yml
- back/backend/src/main/java/org/example/backend/BackendApplication.java
- back/backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- back/backend/src/main/java/org/example/backend/Qna/Repository/ElasticsearchQuestionRepository.java
- back/backend/src/main/java/org/example/backend/Qna/Service/ElasticQnaSearchService.java
- back/backend/src/main/java/org/example/backend/Qna/model/Doc/QnaBoard.java
- back/backend/src/main/resources/application.yml
- back/build.gradle
close #443 
- Elasticsearch 라이브러리 위치 수정(common -> backend)
- 라이브러리 설치시 같이 설치되는 다른 라이브러리의 버전 설정(엘라스틱서치 버전이 자주 바뀜)
- Elasticsearch를 통해 조회할 때 username, password를 입력해야 조회되도록 컨테이너 설정 수정
- 그에 따른 환경변수 추가 -> 노션 확인
- Elasticsearch랑 연동 되는지 확인하기 위한 테스트 용도 코드 작성
- Elasticsearch 컨테이너 delete하고 다시 실행시켜주세요
> [Feat] Elasticsearch 라이브러리 설정 및 테스트 (#443)

- back/backend/src/main/java/org/example/backend/Qna/Service/QnaService.java
- back/backend/src/main/java/org/example/backend/Qna/model/req/GetQnaListReq.java
- back/common/src/main/java/com/example/common/Qna/Repository/QnaRepositoryCustom.java
- back/common/src/main/java/com/example/common/Qna/Repository/QnaRepositoryCustomImpl.java
- back/common/src/main/java/com/example/common/Qna/model/Entity/QnaBoard.java
- back/common/src/main/java/com/example/common/Qna/model/Resolved.java
close #460 
enum 형태의 resolve-state를 qnaBoard에 추가
해당 질문 하위의 답변 리스트의 채택 여부를 확인하여 state 지정 메커니즘 구현
목록 조회 및 검색에서의 resolve-state 연결
> [Feat] qna 목록조회 및 검색에서의 resolved-state 정렬 조건 구현

- back/common/src/main/java/com/example/common/Qna/Repository/QnaRepositoryCustomImpl.java
close #468 
검색 조건에서 adoptedAnswerId가 아닌 resolved/unsolved로 판단
> [Fix] qna search 검색 범위 resolved 범위 지정

- back/backend/elasticsearch/config/index-settings.json
- back/backend/src/main/java/org/example/backend/Config/ElasticSearchConfig.java
- back/backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
- back/backend/src/main/java/org/example/backend/Wiki/Model/Doc/Wiki.java
- back/backend/src/main/java/org/example/backend/Wiki/Model/Req/GetWikiSearchReq.java
- back/backend/src/main/java/org/example/backend/Wiki/Service/DbWikiSearchService.java
- back/backend/src/main/java/org/example/backend/Wiki/Service/ElasticWikiSearchService.java
- back/backend/src/main/java/org/example/backend/Wiki/Service/WikiSearchService.java
close #466 
📌위키 검색에 엘라스틱서치 적용
- RestHighLevelClient를 사용하여 elasticsearch에서 조회
- content에 Fuzziness.AUTO, minimumShouldMatch("75%") 적용
- 검색어의 75%가 포함되는 것만 검색되도록 
- title에 slop(2) 적용
- 각 단어 사이에 두 단어 허용
> [Feat] 위키 검색에 Elasticsearch 도입 (#466)

- back/backend/elasticsearch/config/index-settings.json
- back/backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- back/backend/src/main/java/org/example/backend/Config/ElasticSearchConfig.java
- back/backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
- back/backend/src/main/java/org/example/backend/Qna/Repository/ElasticsearchQuestionRepository.java
- back/backend/src/main/java/org/example/backend/Qna/Service/BasicQnaSearchService.java
- back/backend/src/main/java/org/example/backend/Qna/Service/ElasticQnaSearchService.java
- back/backend/src/main/java/org/example/backend/Qna/Service/QnaSearchService.java
- back/backend/src/main/java/org/example/backend/Qna/model/Doc/QnaBoard.java
- back/backend/src/main/java/org/example/backend/Qna/model/req/GetQnaSearchReq.java
close #465 
- QnA 검색 엘라스틱 서치 도입
- RestHighLevelClient를 사용하여 elasticsearch에서 조회
- title은 각 단어 사이에 두 단어 허용
- content는 검색어의 75%가 포함되는 것만 검색되도록
> [Feat] QnA 검색 엘라스틱 서치 도입 (#465)

- back/backend/src/main/java/org/example/backend/Main/Controller/MainController.java
- back/backend/src/main/java/org/example/backend/Main/Service/MainElasticSearchService.java
close #498 
- setQnaResolvedQuery 메소드 추가
- MultiSearchResponse로 여러 검색 결과 받오게끔 추가
- resthighlevelclient.msearch() 추가: 여러 검색 결과 받아옴
-> 위키 최대 4개, 에러 아카이브 최대 8개, qna 최대 8개 반환하게끔 수정
> [Fix] 통합 검색 사이즈 별로 반환(#498)

- frontend/src/components/Common/SearchComponent.vue
- frontend/src/components/Common/WikiSearchComponent .vue
- frontend/src/components/Header/HeaderComponent.vue
- frontend/src/pages/QnaListPage.vue
- frontend/src/pages/TotalSearchPage.vue
- frontend/src/pages/WikiListPage.vue
- frontend/src/router/index.js
- frontend/src/store/useMainStore.js
close #493 
- 통합 검색 api 호출
- 통합 검색 결과 페이지 생성
- 통합 검색 결과 페이지에서 각 게시판으로 이동 시, 검색이 유지되도록 설정
- 아직 백이 완전하지 않음
> [Feat] 통합 검색 구현 (#493)

- cicd/back/backend.sh
- 백엔드 배포 시 작동되는 script에서 배포된  pod들이 정상 작동하는지 확인하는 rollout 명령어 실행하는 시간 단축 (10초 -> 5초)
- 대신 총 횟수를 10번에서 20번으로 늘림
> [Refactor] 백엔드 cicd 스크립트 rollout 확인 시간 단축

- frontend/src/components/Common/WikiSearchComponent .vue
- frontend/src/components/Common/WikiSortTypeComponent.vue
- frontend/src/pages/WikiListPage.vue
close #558 
- 위키 정렬 컴포넌트 생성
- 검색했을 때만 정렬 컴포넌트 보이도록 설정
> [Feat] 위키 검색 정렬 컴포넌트 추가 (#558)

- frontend/src/components/errorarchive/ErrorArchiveDetailComponent.vue
close #548 
css에 제목 관련한 클래스가 많아서!important 써서 크기를 줄임(우선수위 적용)
> [Fix] 에러아카이브 상세 페이지 글자 크기 수정(#548)

- frontend/src/pages/WikiVersionListPage.vue
close #567 
📌위키 버전리스트 테이블 사이즈 수정
- 리스트 컴포넌트가 짧으면 닉네임 컴포넌트가 짤리는 현상 수정
변경전
변경후
> [Fix] 버전 리스트 테이블 수정 (#567)

- back/backend/src/main/java/org/example/backend/Common/BaseResponseStatus.java
- back/backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java
- back/backend/src/main/java/org/example/backend/ErrorArchive/Model/Res/GetErrorArchiveEditDetailRes.java
- back/backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
- back/common/src/main/java/com/example/common/ErrorArchive/Repository/ErrorArchiveReository.java
close #537 
로그인한 사용자가 작성한 글 수정 가능하게끔 수정
로그인한 사용자가 본인이 작성한 글이 아니면 에러 처리
프론트에서 404 뜨게 하려고 추가한 메소드
> [Feat] 에러 아카이브 수정 권한 설정 추가(#537)

- frontend/src/components/Common/WikiSortTypeComponent.vue
- frontend/src/pages/WikiListPage.vue
- 위키 검색어로 검색했을 때만 sort 검포넌트 보이도록 설정
> [Feat] wiki 검색어로 검색했을 때만 sortcomponent 보이도록 설정
